const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test, before, after } = require('node:test');
const { parse } = require('@babel/parser');
const { PGlite } = require('@electric-sql/pglite');
const { compileQuery, buildSchema } = require('../database/postgres-sql');
const { createQuery, createPostgresPool, poolOptions, parseBigInt } = require('../database/postgres');

const root = path.join(__dirname, '..');
let db;
let query;
before(async () => {
    db = new PGlite({ parsers: { 20: parseBigInt, 1700: Number } });
    await db.exec(buildSchema());
    await db.exec(fs.readFileSync(path.join(root, 'database/runtime.sql'), 'utf8'));
    query = createQuery(db);
});
after(async () => { await db?.close(); });

test('fresh PostgreSQL schema preserves seed settings and can be applied twice', async () => {
    assert.equal(fs.readFileSync(path.join(root, 'database/schema.postgres.sql'), 'utf8'),
        '-- Generated by npm run db:neon:schema from database/schema.sql.\n' + buildSchema());
    const [[before]] = await query('SELECT COUNT(*) AS count FROM gameSettings');
    assert.ok(before.count >= 20);
    await db.exec(buildSchema());
    const [[after]] = await query('SELECT COUNT(*) AS count FROM gameSettings');
    assert.equal(after.count, before.count);
});

test('bound values, literal question marks, mixed-case fields and large IDs survive PostgreSQL round trips', async () => {
    const userId = '76561198012345678';
    const username = "Neon? ' OR 1=1 -- DATE_SUB NOW()";
    await query('INSERT INTO users (id, username, balance) VALUES (?, ?, ?)', [userId, username, 100.25]);
    const [[user]] = await query('SELECT id, username, balance AS currentBalance FROM users WHERE id = ?', [userId]);
    assert.equal(user.id, userId);
    assert.equal(user.username, username);
    assert.equal(user.currentBalance, 100.25);
    assert.equal((await query("SELECT 'literal ?; DATE_SUB' AS content"))[0][0].content, 'literal ?; DATE_SUB');
    const [columns] = await query('DESCRIBE users');
    assert.ok(columns.some(column => column.Field === 'passwordHash'));
});

test('bulk inserts and mixed scalar/array parameters preserve argument order', async () => {
    const [insert] = await query('INSERT INTO tips (fromUserId, toUserId, amount) VALUES ?', [[[1, 2, 3], [1, 3, 4]]]);
    assert.ok(insert.insertId > 0);
    assert.equal(insert.affectedRows, 2);
    const [rows] = await query('SELECT toUserId FROM tips WHERE fromUserId = ? AND toUserId IN (?) AND amount > ? ORDER BY toUserId', [1, [2, 3], 3]);
    assert.deepEqual(rows, [{ toUserId: 3 }]);
    assert.deepEqual((await query('SELECT id FROM tips WHERE toUserId IN (?)', [[]]))[0], []);
    assert.equal((await query('SELECT id FROM tips WHERE toUserId NOT IN (?)', [[]]))[0].length, 2);
    const [roll] = await query('INSERT INTO fairRolls (serverSeed, clientSeed, nonce, seed, result) VALUES (?)', [['s', 'c', 1, 'hash', '0.5']]);
    assert.ok(roll.insertId > 0);
});

test('upserts update existing rows, duplicate ignores leave them intact, and timestamps refresh', async () => {
    await query('INSERT INTO settings (id, value) VALUES (?, ?) ON DUPLICATE KEY UPDATE value = VALUES(value)', ['pg-test', '1']);
    const [[first]] = await query('SELECT updatedAt FROM settings WHERE id = ?', ['pg-test']);
    await query('INSERT INTO settings (id, value) VALUES (?, ?) ON DUPLICATE KEY UPDATE value = VALUES(value)', ['pg-test', '2']);
    const [ignored] = await query('INSERT IGNORE INTO settings (id, value) VALUES (?, ?)', ['pg-test', '3']);
    assert.equal(ignored.affectedRows, 0);
    const [[last]] = await query('SELECT value, updatedAt FROM settings WHERE id = ?', ['pg-test']);
    assert.equal(last.value, '2');
    assert.ok(last.updatedAt >= first.updatedAt);
    await assert.rejects(query('INSERT INTO settings (id, value) VALUES (?, ?)', ['pg-test', '4']), error => error.code === 'ER_DUP_ENTRY');
});

test('provider refresh repairs blank names without replacing account permissions, balances or credentials', async () => {
    const { saveProviderProfile } = require('../routes/auth/profiles');
    const sql = { query };
    await query('INSERT INTO users (id, username, steamId, role, perms, balance, xp, passwordHash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        [777, '   ', '76561198000000777', 'ADMIN', 3, 42.75, 123, 'saved-password-hash']);
    assert.equal(await saveProviderProfile(sql, 'steam', '76561198000000777', {
        username: '玩家 🎮', avatarUrl: 'https://avatars.steamstatic.com/profile.jpg'
    }), 777);
    await saveProviderProfile(sql, 'steam', '76561198000000777', { username: '   ', avatarUrl: 'invalid' });
    const [[saved]] = await query('SELECT username, avatarUrl, role, perms, balance, xp, passwordHash FROM users WHERE id = ?', [777]);
    assert.deepEqual(saved, {
        username: '玩家 🎮', avatarUrl: 'https://avatars.steamstatic.com/profile.jpg',
        role: 'ADMIN', perms: 3, balance: 42.75, xp: 123, passwordHash: 'saved-password-hash'
    });
    const fallbackId = await saveProviderProfile(sql, 'google', '11223344556600000777', { username: ' \n ' });
    const [[fallback]] = await query('SELECT username FROM users WHERE id = ?', [fallbackId]);
    assert.equal(fallback.username, 'User000777');
});

test('date arithmetic accepts bound intervals and nested dashboard week calculations', async () => {
    const [[row]] = await query("SELECT DATE_SUB(NOW(), INTERVAL ? SECOND) AS cutoff, DATE_FORMAT(DATE_ADD(DATE_SUB(createdAt, INTERVAL WEEKDAY(createdAt) DAY), INTERVAL 6 DAY), '%d/%m/%Y') AS weekEnd FROM users WHERE id = ?", [3600, '76561198012345678']);
    assert.ok(Math.abs(row.cutoff.valueOf() - (Date.now() - 3600000)) < 10000);
    assert.match(row.weekEnd, /^\d{2}\/\d{2}\/\d{4}$/);
});

test('account deletion guards permissions and preserves ledger history while removing access and profile data', async () => {
    const { deleteUserAccount } = require('../routes/admin/users/delete');
    const { saveProviderProfile } = require('../routes/auth/profiles');
    const connection = { query };
    const actor = { id: 901, role: 'OWNER', perms: 4 };
    await query('INSERT INTO users (id, username, role, perms, balance, steamId, passwordHash, avatarUrl) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        [902, 'Delete test', 'USER', 0, 42.5, '76561198000000902', 'hash', 'https://avatars.steamstatic.com/test.jpg']);
    await query('INSERT INTO transactions (userId, amount, type, method) VALUES (?, ?, ?, ?)', [902, 42.5, 'in', 'admin']);
    for (const [admin, id, confirmation, code] of [
        [actor, '901', '901', 'CANNOT_DELETE_SELF'],
        [{...actor, role: 'USER'}, '902', '902', 'CANNOT_DELETE_USER'],
        [{...actor, perms: 0}, '902', '902', 'CANNOT_DELETE_USER'],
        [actor, '902', '', 'DELETE_CONFIRMATION_REQUIRED'],
        [actor, 'invalid', 'invalid', 'INVALID_USER_ID'],
    ]) {
        await assert.rejects(deleteUserAccount(connection, admin, id, confirmation), {message: code});
    }
    await query('BEGIN');
    await deleteUserAccount(connection, actor, '902', '902');
    await query('ROLLBACK');
    assert.equal((await query('SELECT username FROM users WHERE id = ?', [902]))[0][0].username, 'Delete test');
    await query('BEGIN');
    await deleteUserAccount(connection, actor, '902', '902');
    await query('COMMIT');
    const [[user]] = await query('SELECT * FROM users WHERE id = ?', [902]);
    assert.equal(user.username, 'Deleted user');
    assert.equal(user.passwordHash, null);
    assert.equal(user.avatarUrl, null);
    assert.equal(user.banned, 1);
    assert.equal(user.balance, 42.5);
    assert.equal(user.deletedBy, actor.id);
    assert.ok(user.deletedAt);
    assert.equal((await query('SELECT amount FROM transactions WHERE userId = ?', [902]))[0][0].amount, 42.5);
    await assert.rejects(saveProviderProfile(connection, 'steam', '76561198000000902', {username: 'Restore?'}), {message: 'ACCOUNT_DELETED'});
    await assert.rejects(deleteUserAccount(connection, actor, '902', '902'), {message: 'USER_NOT_FOUND'});
});

test('transaction wrapper uses one checked-out client and rolls back balance changes', async () => {
    let acquired = 0;
    let released = 0;
    class TestPool {
        on() {}
        query() { throw new Error('Transactions must not query the pool'); }
        async connect() {
            acquired++;
            return { query: (text, values) => db.query(text, values), release: () => released++ };
        }
    }
    const pool = createPostgresPool('postgres://local:test@localhost/test', TestPool);
    const connection = await pool.getConnection();
    try {
        await connection.beginTransaction();
        await connection.query('SELECT id FROM users WHERE id = ? FOR UPDATE', ['76561198012345678']);
        await connection.query('UPDATE users SET balance = balance - ? WHERE id = ?', [25, '76561198012345678']);
        await connection.rollback();
        assert.equal((await query('SELECT balance FROM users WHERE id = ?', ['76561198012345678']))[0][0].balance, 100.25);
        await connection.beginTransaction();
        await connection.query('UPDATE users SET balance = balance - ? WHERE id = ?', [25, '76561198012345678']);
        await connection.commit();
        assert.equal((await query('SELECT balance FROM users WHERE id = ?', ['76561198012345678']))[0][0].balance, 75.25);
    } finally {
        connection.release();
    }
    assert.equal(acquired, 1);
    assert.equal(released, 1);
});

test('Neon pool validates the URL, verifies TLS and preserves unsafe BIGINT values', () => {
    assert.throws(() => poolOptions(''), /requires DATABASE_URL/);
    assert.throws(() => poolOptions('mysql://localhost/test'), /postgres/);
    assert.match(poolOptions('postgres://test:secret@ep-test-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require').connectionString, /sslmode=verify-full/);
    assert.equal(parseBigInt('123'), 123);
    assert.equal(parseBigInt('76561198012345678'), '76561198012345678');
});

test('roulette settles green at 14x and both bait numbers at 7x using PostgreSQL transactions', async () => {
    const module = { exports: {} };
    const dependencies = {
        '../../../database': { sql: { query } },
        '../../../socketio/bets': {},
        '../../../utils': { roundDecimal: value => Math.floor(value * 100) / 100 },
        '../../../routes/admin/gameConfig': { getGameConfig: (game, key, fallback) => fallback },
        '../../../fairness': {},
        '../../../socketio/server': {},
        crypto: require('node:crypto'),
        './bonus': require('../routes/games/roulette/bonus'),
    };
    vm.runInNewContext(fs.readFileSync(path.join(root, 'routes/games/roulette/functions.js'), 'utf8'), {
        module,
        require: name => {
            if (!(name in dependencies)) throw new Error(`Unexpected dependency: ${name}`);
            return dependencies[name];
        },
    });
    const { settleRouletteBets, resultToColor } = module.exports;
    for (const [result, expected] of [[0, [140, 0, 0, 0]], [7, [0, 20, 0, 70]], [8, [0, 0, 20, 70]], [1, [0, 20, 0, 0]], [14, [0, 0, 20, 0]]]) {
        await db.query('BEGIN');
        try {
            await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 0)', [900001, 'roulette-test']);
            const bets = [];
            for (const color of [0, 1, 2, 3]) {
                const [bet] = await query('INSERT INTO rouletteBets (userId, roundId, color, amount) VALUES (?, ?, ?, ?)', [900001, 900001, color, 10]);
                await query('INSERT INTO bets (userId, amount, game, gameId, completed) VALUES (?, ?, ?, ?, ?)', [900001, 10, 'roulette', bet.insertId, 0]);
                bets.push({ id: bet.insertId, user: { id: 900001 }, color, amount: 10 });
            }
            await settleRouletteBets({ query }, { result, color: resultToColor(result) }, bets);
            const [settled] = await query('SELECT winnings, completed FROM bets WHERE userId = ? ORDER BY id', [900001]);
            assert.deepEqual(settled.map(bet => bet.winnings), expected);
            assert.ok(settled.every(bet => bet.completed === 1));
            const [[user]] = await query('SELECT balance FROM users WHERE id = ?', [900001]);
            assert.equal(user.balance, expected.reduce((sum, payout) => sum + payout, 0));
        } finally { await db.query('ROLLBACK'); }
        assert.deepEqual((await query('SELECT id FROM users WHERE id = ?', [900001]))[0], []);
    }
});

test('wheel bonus preserves tiny contributions and rolls back with the bet', async () => {
    const {addContribution} = require('../routes/games/roulette/bonus');
    await db.query('BEGIN');
    try {
        await query('DELETE FROM settings WHERE id = ?', ['rouletteTripleGreenBonusPot']);
        let pot;
        for (let i = 0; i < 100; i++) pot = await addContribution({query}, .01, .66);
        assert.equal(pot, .0066);
        assert.equal(await addContribution({query}, 100, .66), .6666);
    } finally { await db.query('ROLLBACK'); }
    assert.equal((await query('SELECT value FROM settings WHERE id = ?', ['rouletteTripleGreenBonusPot']))[0].length, 0);
});

test('wheel bonus pays three independent green rounds once, carries empty shares, and records payouts', async () => {
    const {distributeBonus, loadBonus} = require('../routes/games/roulette/bonus');
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 0)', [900101, 'green-one']);
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 0)', [900102, 'green-two']);
        await query('INSERT INTO settings (id, value) VALUES (?, ?)', ['rouletteTripleGreenBonusPot', '90.000066']);
        for (const id of [900101,900102,900103]) {
            await query('INSERT INTO roulette (id, result, color, endedAt) VALUES (?, 0, 0, CURRENT_TIMESTAMP)', [id]);
        }
        for (const [user, round, color, amount] of [[900101,900101,0,50],[900102,900101,0,50],[900101,900102,0,10],[900102,900103,1,100]]) {
            await query('INSERT INTO rouletteBets (userId, roundId, color, amount) VALUES (?, ?, ?, ?)', [user,round,color,amount]);
        }
        const result = await distributeBonus({query});
        assert.equal(result.distributed, 60);
        assert.equal(result.carriedOver, 30.000066);
        assert.deepEqual(result.payouts.map(p => p.amount), [45,15]);
        assert.equal((await query("SELECT SUM(amount) AS total FROM transactions WHERE method = 'roulette-bonus'"))[0][0].total, 60);
        assert.equal(await distributeBonus({query}), null);
        assert.equal((await loadBonus({query})).streak, 0);
        await query('INSERT INTO roulette (id, result, color, endedAt) VALUES (?, 0, 0, CURRENT_TIMESTAMP)', [900104]);
        assert.equal(await distributeBonus({query}), null, 'fourth green must not reuse the previous paid streak');
        assert.equal((await loadBonus({query})).streak, 1);
        for (const id of [900105,900106]) await query('INSERT INTO roulette (id, result, color, endedAt) VALUES (?, 0, 0, CURRENT_TIMESTAMP)', [id]);
        const empty = await distributeBonus({query});
        assert.equal(empty.distributed, 0);
        assert.equal(empty.carriedOver, 30.000066);
        assert.equal(await distributeBonus({query}), null);
    } finally { await db.query('ROLLBACK'); }
});

test('wheel bonus cent allocation conserves the entire eligible round share', () => {
    const {allocateShare} = require('../routes/games/roulette/bonus');
    const result = allocateShare(100, [{userId:1,amount:1},{userId:2,amount:1},{userId:3,amount:1}]);
    assert.deepEqual(result.map(p => p.cents), [34,33,33]);
});

test('roulette bet route funds the pot from every color and never from rejected bets', async () => {
    const {addContribution} = require('../routes/games/roulette/bonus');
    const roulette = {round:{id:900201},bets:[],config:{maxBet:25000},tripleGreenBonusPot:0};
    const dependencies = {
        express: require('express'),
        '../../../runtime/context': { enabled: false },
        '../../../database': {doTransaction: async fn => {
            await db.query('SAVEPOINT test_bet');
            let committed = false;
            try {return await fn({query}, async () => {committed = true;});}
            finally {if (!committed) await db.query('ROLLBACK TO SAVEPOINT test_bet');await db.query('RELEASE SAVEPOINT test_bet');}
        }},
        '../../auth/functions': {isAuthed(){},apiLimiter(){}},
        '../../../utils': {roundDecimal: n => Math.floor(Number(n)*100)/100,xpChanged:async()=>{}},
        '../../../socketio/server': {to:()=>({emit(){}})},
        './functions': {roulette,addToTripleGreenBonus:(connection,amount)=>addContribution(connection,amount,.66)},
        '../../admin/config': {enabledFeatures:{roulette:true},xpMultiplier:1}
    };
    const context = {module:{exports:{}},console,require:name=>{
        if (!(name in dependencies)) throw new Error(`Unexpected dependency ${name}`);
        return dependencies[name];
    }};
    vm.runInNewContext(fs.readFileSync(path.join(root,'routes/games/roulette/index.js'),'utf8'),context);
    const handler=context.module.exports.stack.find(layer=>layer.route?.path==='/bet').route.stack.at(-1).handle;
    const request=async(userId,body)=>{
        const res={status(){return this;},json(body){this.body=body;return this;}};
        await handler({userId,body},res);return res.body;
    };
    await db.query('BEGIN');
    try {
        await query('INSERT INTO roulette (id, result, color) VALUES (?, 0, 0)',[900201]);
        for (const color of [0,1,2,3]) {
            const userId=900201+color;
            await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 200)',[userId,`bettor-${color}`]);
            assert.equal((await request(userId,{color,amount:100})).success,true);
        }
        assert.equal(roulette.tripleGreenBonusPot,2.64);
        assert.equal((await request(900201,{color:0,amount:200})).error,'INSUFFICIENT_BALANCE');
        assert.equal((await query('SELECT value FROM settings WHERE id = ?',['rouletteTripleGreenBonusPot']))[0][0].value,'2.640000');
        await query('UPDATE roulette SET rolledAt = CURRENT_TIMESTAMP WHERE id = ?',[900201]);
        assert.equal((await request(900201,{color:0,amount:1})).error,'ALREADY_STARTED');
        assert.equal((await query('SELECT balance FROM users WHERE id = ?',[900201]))[0][0].balance,100);
    } finally {await db.query('ROLLBACK');}
});

function walk(node, visit) {
    if (!node || typeof node !== 'object') return;
    visit(node);
    for (const [key, value] of Object.entries(node)) {
        if (key === 'loc') continue;
        if (Array.isArray(value)) value.forEach(child => walk(child, visit));
        else if (value && typeof value === 'object') walk(value, visit);
    }
}

test('PostgreSQL plans every static query in active HTTP routes and socket handlers', async () => {
    const seen = new Set();
    const failures = [];
    let checked = 0;
    for (const dir of ['routes', 'socketio', 'fairness']) {
        for (const file of fs.readdirSync(path.join(root, dir), { recursive: true }).filter(file => file.endsWith('.js'))) {
            const filename = path.join(dir, file);
            // Jackpot was removed by migration 006 and has no mounted route.
            if (filename.includes(`${path.sep}jackpot${path.sep}`)) continue;
            const ast = parse(fs.readFileSync(path.join(root, filename), 'utf8'), { sourceType: 'unambiguous' });
            const queries = [];
            walk(ast, node => {
                if (node.type !== 'CallExpression' || node.callee?.property?.name !== 'query') return;
                const arg = node.arguments[0];
                const sql = arg?.type === 'StringLiteral' ? arg.value : arg?.type === 'TemplateLiteral' && !arg.expressions.length ? arg.quasis[0].value.cooked : null;
                if (sql && /^(SELECT|INSERT|UPDATE|DELETE)/i.test(sql.trim()) && !seen.has(sql)) {
                    seen.add(sql);
                    queries.push({ sql, line: node.loc.start.line });
                }
            });
            for (const { sql, line } of queries) {
                const params = new Array((sql.match(/\?/g) || []).length).fill(null);
                const bulk = sql.match(/INSERT.*?\(([^)]+)\)\s*VALUES\s*(\(\?\)|\?)/is);
                if (bulk) {
                    const row = new Array(bulk[1].split(',').length).fill(null);
                    params[0] = bulk[2] === '?' ? [row] : row;
                }
                try {
                    const compiled = compileQuery(sql, params);
                    await db.query('EXPLAIN ' + compiled.text, compiled.values);
                    checked++;
                } catch (error) { failures.push(`${filename}:${line}: ${error.message}`); }
            }
        }
    }
    assert.deepEqual(failures, []);
    assert.ok(checked > 400, `Expected broad query coverage, got ${checked}`);
});

function loadRouteModule(file, dependencies) {
    const context = {module:{exports:{}},console,Buffer,process,setTimeout,clearTimeout,require:name=>{
        if (Object.hasOwn(dependencies, name)) return dependencies[name];
        if (name.endsWith('/runtime/context')) return { enabled: false, tracked: fn => fn };
        if (['express','crypto'].includes(name)) return require(name);
        if (name === '../../../fairness/randomorg') return {...require('../fairness/randomorg'),createTicket:async()=> '0123456789abcdef'};
        if (name === './fairness') return {};
        throw new Error(`Unexpected dependency ${name}`);
    }};
    vm.runInNewContext(fs.readFileSync(path.join(root,file),'utf8'),context);
    return context.module.exports;
}

function transactionFixture() {
    return {sql:{query},doTransaction: async fn => {
        await db.query('SAVEPOINT route_test');
        let committed=false;
        try {return await fn({query},async()=>{committed=true;});}
        finally {if(!committed)await db.query('ROLLBACK TO SAVEPOINT route_test');await db.query('RELEASE SAVEPOINT route_test');}
    }};
}
const routeUtils = {roundDecimal:n=>Math.round(Number(n)*100)/100,xpChanged:async()=>{},getUserLevel:()=>1,sendLog(){},newNotification:async()=>{}};
async function invokeRoute(router, path, userId, body, params={}) {
    const handler=router.stack.find(layer=>layer.route?.path===path).route.stack.at(-1).handle;
    const res={statusCode:200,status(n){this.statusCode=n;return this;},json(data){this.body=data;return this;}};
    await handler({userId,body,params},res);
    return res;
}

test('fresh case feature and first-ever six-case opening persist all results and the nonce', async()=>{
    assert.equal((await query('SELECT enabled FROM features WHERE id = ?',['cases']))[0][0].enabled,1);
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 100)',[900301,'case test']);
        const [c]=await query('INSERT INTO cases (name, slug) VALUES (?, ?)',['Test case','route-case-test']);
        const [v]=await query('INSERT INTO caseVersions (caseId, price) VALUES (?, 2)',[c.insertId]);
        await query('INSERT INTO caseItems (caseVersionId, name, price, rangeFrom, rangeTo) VALUES (?, ?, 1, 1, 100000)',[v.insertId,'Test drop']);
        const fairness=loadRouteModule('fairness/index.js',{'../database':{sql:{query}}});
        const router=loadRouteModule('routes/games/cases/index.js',{
            '../../../database':transactionFixture(), '../../auth/functions':{isAuthed(){},apiLimiter(){}},
            '../../../utils':routeUtils,'../../../fairness':fairness,
            './functions':{mapItem:i=>i,newDrops(){},cachedCases:{},ensureCasesCacheFresh:async()=>{}},
            '../../../socketio/server':{to:()=>({emit(){}})},'../../../socketio/bets':{newBets(){}},
            './community':{router:require('express').Router()},'../../admin/config':{enabledFeatures:{cases:true},xpMultiplier:1},
            '../../admin/gameConfig':{getGameConfig:(game,key,fallback)=>fallback}
        });
        const result=await invokeRoute(router,'/:id/open',900301,{amount:6},{id:c.insertId});
        assert.equal(result.statusCode,200);assert.equal(result.body.results.length,6);assert.equal(result.body.balance,94);
        assert.equal((await query('SELECT nonce FROM serverSeeds WHERE userId = ?',[900301]))[0][0].nonce,6);
        assert.equal((await query('SELECT COUNT(*) as n FROM caseOpenings WHERE userId = ?',[900301]))[0][0].n,6);
        await query('UPDATE users SET balance = 0 WHERE id = ?',[900301]);
        assert.equal((await invokeRoute(router,'/:id/open',900301,{amount:1},{id:c.insertId})).body.error,'INSUFFICIENT_BALANCE');
        assert.equal((await query('SELECT nonce FROM serverSeeds WHERE userId = ?',[900301]))[0][0].nonce,6);
    }finally{await db.query('ROLLBACK');}
});

test('battle creation charges the correct amount and saves its rounds on PostgreSQL', async()=>{
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 100)',[900302,'battle test']);
        const [c]=await query('INSERT INTO cases (name, slug) VALUES (?, ?)',['Battle case','route-battle-test']);
        await query('INSERT INTO caseVersions (caseId, price) VALUES (?, 2)',[c.insertId]);
        let ticketAvailable=true;
        const router=loadRouteModule('routes/games/battles/index.js',{
            '../../../database':transactionFixture(),'../../auth/functions':{isAuthed(){},apiLimiter(){}},
            '../../../utils':routeUtils,'../../../fairness':{generateServerSeed:()=> 'test',sha256:s=>s},
            '../cases/functions':{mapItem:i=>i},'./functions':{cachedBattles:{},minifyBattle:b=>b,newBattlePlayer(){},startBattle(){}},
            './bots':require('../routes/games/battles/bots'),
            '../../../fairness/randomorg':{createTicket:async()=>{if(!ticketAvailable)throw Error('RANDOM_ORG_UNAVAILABLE');return '0123456789abcdef';}},
            '../../admin/config':{enabledFeatures:{battles:true},xpMultiplier:1},
            '../../../socketio/server':{to:()=>({emit(){}})},'p-queue':{default:class {}}
        });
        const res=await invokeRoute(router,'/create',900302,{cases:[c.insertId,c.insertId],gamemode:'standard',teams:2,playersPerTeam:1,funding:0,minLvl:0,isPrivate:false});
        assert.equal(res.statusCode,200);assert.equal(res.body.success,true);
        assert.equal((await query('SELECT balance FROM users WHERE id = ?',[900302]))[0][0].balance,96);
        assert.equal((await query('SELECT COUNT(*) as n FROM battleRounds WHERE battleId = ?',[res.body.battleId]))[0][0].n,2);
        assert.equal((await query('SELECT randomTicket FROM battles WHERE id = ?',[res.body.battleId]))[0][0].randomTicket,'0123456789abcdef');
        ticketAvailable=false;
        const failed=await invokeRoute(router,'/create',900302,{cases:[c.insertId],gamemode:'standard',teams:2,playersPerTeam:1,funding:0,minLvl:0,isPrivate:false});
        assert.equal(failed.body.error,'RANDOM_ORG_UNAVAILABLE');
        assert.equal((await query('SELECT balance FROM users WHERE id = ?',[900302]))[0][0].balance,96);
        assert.equal((await query('SELECT COUNT(*) AS n FROM battles WHERE ownerId = ?',[900302]))[0][0].n,1);

    }finally{await db.query('ROLLBACK');}
});

test('battle bot provisioning is idempotent and never changes an existing user', async () => {
    const { ensureBattleBots, findBattleBot } = require('../routes/games/battles/bots');
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 37)', [8000000000000001, 'Existing user']);
        await ensureBattleBots({ query });
        await ensureBattleBots({ query });
        const [[user]] = await query('SELECT role, balance FROM users WHERE id = ?', [8000000000000001]);
        assert.deepEqual(user, { role: 'USER', balance: 37 });
        const [bots] = await query('SELECT id, balance, perms, passwordHash FROM users WHERE role = ?', ['BOT']);
        assert.equal(bots.length, 7);
        assert.ok(bots.every(bot => bot.balance === 0 && bot.perms === 0 && bot.passwordHash === null));
        await query('UPDATE users SET banned = 1 WHERE id = ?', [bots[0].id]);
        await query('UPDATE users SET deletedAt = NOW() WHERE id = ?', [bots[1].id]);
        const bot = await findBattleBot({ query }, [bots[2].id]);
        assert.equal(bot.id, bots[3].id);
    } finally { await db.query('ROLLBACK'); }
});

test('bot pool grows when seeded accounts are unavailable and keeps generated names stable', async () => {
    const { ensureBattleBots, findBattleBot } = require('../routes/games/battles/bots');
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, role) VALUES (?, ?, ?)', [8000000000000001, 'Cosmic Bot 1', 'BOT']);
        await ensureBattleBots({ query });
        const [initial] = await query('SELECT id, username FROM users WHERE role = ? ORDER BY id', ['BOT']);
        assert.equal(initial.length, 8);
        assert.ok(initial.every(bot => /^Bob#\d{3}$/.test(bot.username)));
        await ensureBattleBots({ query });
        assert.deepEqual((await query('SELECT id, username FROM users WHERE role = ? ORDER BY id', ['BOT']))[0], initial);
        await query('UPDATE users SET banned = 1 WHERE role = ?', ['BOT']);
        const first = await findBattleBot({ query }, []);
        const second = await findBattleBot({ query }, [first.id]);
        assert.match(first.username, /^Bob#\d{3}$/);
        assert.match(second.username, /^Bob#\d{3}$/);
        assert.notEqual(first.id, second.id);
        assert.ok(!initial.some(bot => bot.id === first.id || bot.id === second.id));
        assert.equal((await query('SELECT COUNT(*) AS n FROM users WHERE role = ? AND banned = 1', ['BOT']))[0][0].n, 8);
        assert.equal((await findBattleBot({ query }, [])).id, Math.min(first.id, second.id));
    } finally { await db.query('ROLLBACK'); }
});

for (const resumeFinalRound of [false, true, 'vercel']) test(`Call Bot provisions seats and ${resumeFinalRound ? 'resumes final-round settlement' : 'starts and settles a battle'}`, async () => {
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 100)', [900304, 'Bot battle owner']);
        const [c] = await query('INSERT INTO cases (name, slug) VALUES (?, ?)', ['Bot test', 'bot-test']);
        const [v] = await query('INSERT INTO caseVersions (caseId, price) VALUES (?, 2)', [c.insertId]);
        await query('INSERT INTO caseItems (caseVersionId, name, price, rangeFrom, rangeTo) VALUES (?, ?, 1.11, 1, 100000)', [v.insertId, 'Bot test drop']);
        const [b] = await query('INSERT INTO battles (ownerId, entryPrice, teams, playersPerTeam, gamemode, serverSeed) VALUES (?, 2, 2, 2, ?, ?)', [900304, 'standard', 'test-server-seed']);
        await query('INSERT INTO battleRounds (battleId, caseVersionId, round) VALUES ?', [[[b.insertId, v.insertId, 1], [b.insertId, v.insertId, 2]]]);
        await query('INSERT INTO battlePlayers (battleId, userId, slot, team) VALUES (?, ?, 1, 1)', [b.insertId, 900304]);
        const bots = require('../routes/games/battles/bots');
        const events = [];
        const io = { to: () => ({ emit: (...args) => events.push(args) }) };
        const fairness = { generateServerSeed: () => 'seed', sha256: s => s, combine: (...parts) => parts.join('-'), getResult: () => 1 };
        const functions = loadRouteModule('routes/games/battles/functions.js', {
            '../../../database': transactionFixture(), '../../../utils': { ...routeUtils, sleep: async () => {} },
            '../../../runtime/context': { enabled: resumeFinalRound === 'vercel', tracked: fn => fn },
            '../../../socketio/server': io, '../cases/functions': { mapItem: i => i },
            '../../../fairness/eos': { getEOSBlockNumber: async () => 100, waitForEOSBlock: async () => 'test-block-hash' },
            '../../../socketio/bets': { newBets() {} }, '../../../fairness': fairness,
            '../../../routes/admin/gameConfig': { getGameConfig: (game, key, fallback) => fallback }, './bots': bots,
        });
        const cached = await functions.getBattle(b.insertId);
        let starts = 0;
        let startArgs;
        const router = loadRouteModule('routes/games/battles/index.js', {
            '../../../database': transactionFixture(), '../../auth/functions': { isAuthed() {}, apiLimiter() {} },
            '../../../utils': routeUtils, '../../../fairness': fairness, '../cases/functions': { mapItem: i => i },
            './functions': { ...functions, startBattle: async (...args) => { starts++; startArgs = args; } }, './bots': bots,
            '../../admin/config': { enabledFeatures: { battles: true }, xpMultiplier: 1 },
            '../../../socketio/server': io, 'p-queue': require('p-queue'),
        });
        const call = (slot, userId = 900304) => invokeRoute(router, '/:id/bot', userId, { slot }, { id: b.insertId });
        assert.equal((await call(2, 900305)).statusCode, 403);
        assert.equal((await query('SELECT COUNT(*) AS n FROM users WHERE role = ?', ['BOT']))[0][0].n, 0);
        assert.equal((await call(5)).body.error, 'INVALID_SLOT');
        assert.equal((await call(4)).body.success, true);
        const duplicates = await Promise.all([call(2), call(2)]);
        assert.equal(duplicates.filter(r => r.body.success).length, 1);
        assert.equal(duplicates.filter(r => r.body.error === 'SLOT_TAKEN').length, 1);
        assert.equal(starts, 0);
        assert.equal((await call(3)).body.success, true);
        assert.equal(starts, 1);
        assert.deepEqual(startArgs[1].map(p => p.slot), [1, 2, 3, 4]);
        assert.ok(startArgs[1].slice(1).every(p => p.role === 'BOT'));
        assert.equal(new Set(cached.players.map(p => p.id)).size, 4);
        assert.equal((await query('SELECT COUNT(*) AS n FROM bets WHERE gameId = ?', [b.insertId]))[0][0].n, 3);
        assert.equal((await query('SELECT balance FROM users WHERE id = ?', [900304]))[0][0].balance, 100);
        if (resumeFinalRound) {
            await query('UPDATE battles SET round = 2, startedAt = NOW(), clientSeed = ?, EOSBlock = 102 WHERE id = ?', ['test-block-hash', b.insertId]);
            if (resumeFinalRound === 'vercel') await query('UPDATE battles SET startedAt = ? WHERE id = ?', [new Date(Date.now() - 60000), b.insertId]);
            startArgs[0] = (await query('SELECT * FROM battles WHERE id = ?', [b.insertId]))[0][0];
            cached.startedAt = new Date();
        }
        await functions.startBattle(...startArgs);
        const [[ended]] = await query('SELECT round, startedAt, endedAt, winnerTeam FROM battles WHERE id = ?', [b.insertId]);
        assert.equal(ended.round, 2);
        assert.ok(ended.startedAt && ended.endedAt);
        assert.equal(ended.winnerTeam, 2);
        const [winningBets] = await query('SELECT winnings FROM bets WHERE gameId = ? AND winnings > 0', [b.insertId]);
        assert.equal(winningBets.length, 2);
        assert.ok(winningBets.every(bet => bet.winnings === 4.44), 'Fractional winnings must not be inferred as integers');
        assert.equal(events.some(e => e[0] === 'battle:start'), !resumeFinalRound);
        assert.ok(events.some(e => e[0] === 'battle:ended'));
        assert.equal((await query('SELECT COUNT(*) AS n FROM battleOpenings WHERE battleId = ?', [b.insertId]))[0][0].n, resumeFinalRound ? 0 : 8);
        const eventCount = events.length;
        await functions.startBattle(...startArgs);
        assert.equal(events.length, eventCount, 'Already settled battle must not publish or pay again');
        assert.ok((await query('SELECT balance FROM users WHERE role = ?', ['BOT']))[0].every(bot => bot.balance === 0));
        assert.equal((await call(2)).body.error, 'ALREADY_STARTED');
    } finally { await db.query('ROLLBACK'); }
});

test('gift cards accept formatted codes once and reject reused or invalid codes without credit', async()=>{
    assert.equal((await query('SELECT enabled FROM features WHERE id = ?',['fiatDeposits']))[0][0].enabled,1);
    await db.query('BEGIN');
    try {
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 0)',[900303,'gift test']);
        await query('INSERT INTO giftCards (code, amount, usd) VALUES (?, 25, 0)',['abcdefghijklmnop']);
        const router=loadRouteModule('routes/trading/deposit/giftcards.js',{
            '../../../database':transactionFixture(),'../../auth/functions':{isAuthed(){},apiLimiter(){}},
            '../../../utils':routeUtils,'../../../socketio/server':{to:()=>({emit(){}})},
            '../../admin/config':{enabledFeatures:{fiatDeposits:true},depositBonus:0},
            '../crypto/deposit/functions':{cryptoData:{}},'../../user/rewards/functions':{activateDepositRewards:async()=>{}}
        });
        assert.equal((await invokeRoute(router,'/redeem',900303,{code:' ABCD-EFGH-IJKL-MNOP '})).body.success,true);
        assert.equal((await invokeRoute(router,'/redeem',900303,{code:'ABCD-EFGH-IJKL-MNOP'})).body.error,'INVALID_CODE');
        assert.equal((await invokeRoute(router,'/redeem',900303,{code:'bad'})).body.error,'INVALID_CODE');
        assert.equal((await query('SELECT balance FROM users WHERE id = ?',[900303]))[0][0].balance,25);
    }finally{await db.query('ROLLBACK');}
});


test('RANDOM.ORG battle fails closed, resumes with committed proof, and exposes verifiable rounds', async () => {
    await db.query('BEGIN');
    try {
        const real = loadRouteModule('fairness/index.js', {'../database':{sql:{query}}});
        const randomorg = require('../fairness/randomorg');
        await query('INSERT INTO users (id, username, balance) VALUES (?, ?, 100)', [900310,'Signed owner']);
        await query('INSERT INTO users (id, username, role) VALUES (?, ?, ?)', [900311,'Bob#804','BOT']);
        const [c]=await query('INSERT INTO cases (name, slug) VALUES (?, ?)', ['Signed case','signed-case-test']);
        const [v]=await query('INSERT INTO caseVersions (caseId, price) VALUES (?, 1)',[c.insertId]);
        await query('INSERT INTO caseItems (caseVersionId, name, price, rangeFrom, rangeTo) VALUES (?, ?, 1.11, 1, 100000)',[v.insertId,'Signed drop']);
        const [b]=await query('INSERT INTO battles (ownerId,entryPrice,teams,playersPerTeam,gamemode,serverSeed,randomTicket,privKey) VALUES (?,1,2,1,?,?,?,?)',[900310,'standard','committed-seed','0123456789abcdef','test']);
        await query('INSERT INTO battleRounds (battleId,caseVersionId,round) VALUES ?',[[[b.insertId,v.insertId,1],[b.insertId,v.insertId,2]]]);
        await query('INSERT INTO battlePlayers (battleId,userId,slot,team) VALUES ?',[[[b.insertId,900310,1,1],[b.insertId,900311,2,2]]]);
        const events=[];let unavailable=true,draws=0;
        const proof={random:{data:['abcdef0123456789abcdef0123456789']},signature:'test'};
        const fairness=loadRouteModule('routes/games/battles/fairness.js',{'../../../database':{sql:{query}},'../../../fairness':real,'../../../fairness/randomorg':{...randomorg,verifyProof:()=>true}});
        let status=await fairness.getBattleFairness(b.insertId,'test');
        assert.equal(status.serverSeed,null);assert.equal(status.serverSeedHash,real.sha256('committed-seed'));
        assert.equal(await fairness.getBattleFairness(b.insertId),null);
        const functions=loadRouteModule('routes/games/battles/functions.js',{
            '../../../database':transactionFixture(),'../../../utils':{...routeUtils,sleep:async()=>{}},
            '../../../socketio/server':{to:()=>({emit:(...args)=>events.push(args)})},'../cases/functions':{mapItem:i=>i},
            '../../../fairness/eos':{getEOSBlockNumber:()=>{throw Error('Must not fall back to EOS')}},
            '../../../socketio/bets':{newBets(){}},'../../../fairness':real,
            '../../../routes/admin/gameConfig':{getGameConfig:(g,k,v)=>v},'./bots':require('../routes/games/battles/bots'),
            '../../../fairness/randomorg':{...randomorg,drawSeed:async battle=>{draws++;assert.equal(battle.randomTicket,'0123456789abcdef');if(unavailable)throw Error('RANDOM_ORG_UNAVAILABLE');return {clientSeed:proof.random.data[0],proof};}},
        });
        const cached=await functions.getBattle(b.insertId,'test');
        const stored=(await query('SELECT * FROM battles WHERE id = ?',[b.insertId]))[0][0];
        await functions.startBattle(stored,cached.players);
        assert.equal((await query('SELECT COUNT(*) AS n FROM battleOpenings WHERE battleId = ?',[b.insertId]))[0][0].n,0);
        assert.ok(events.some(e=>e[0]==='battle:fairness'&&e[2].status==='pending'));
        unavailable=false;
        await Promise.all([functions.startBattle(stored,cached.players),functions.startBattle(stored,cached.players)]);
        status=await fairness.getBattleFairness(b.insertId,'test');
        assert.equal(status.status,'finished');assert.equal(status.provider,'RANDOM.ORG');assert.equal(status.serverSeed,'committed-seed');
        assert.equal(status.signatureVerified,true);assert.equal(draws,2);
        assert.equal(status.rounds.flatMap(r=>r.rolls).length,4);
        for(const roll of status.rounds.flatMap(r=>r.rolls)) {
            assert.equal(roll.seed,real.combine(status.serverSeed,status.clientSeed,roll.nonce));
            assert.equal(Number(roll.result),randomorg.ticketFromDigest(roll.seed));
        }
        await functions.startBattle(stored,cached.players);assert.equal(draws,2);
        const balances=(await query('SELECT id,balance FROM users WHERE id IN (?)',[[900310,900311]]))[0];
        assert.equal(balances.find(p=>p.id===900311).balance,0);
        assert.ok([100,104.44].includes(balances.find(p=>p.id===900310).balance));
    } finally {await db.query('ROLLBACK');}
});

test('bot drops and wins are excluded from historical and live public feeds without hiding human drops', async()=>{
    await db.query('BEGIN');
    try {
        const human={id:900801,username:'Bob#123',role:'USER',xp:0};
        const bot={id:900802,username:'Robot',role:'BOT',xp:0};
        await query('INSERT INTO users (id, username, role) VALUES (?, ?, ?), (?, ?, ?)',[human.id,human.username,human.role,bot.id,bot.username,bot.role]);
        const [c]=await query('INSERT INTO cases (name, slug) VALUES (?, ?)',['Feed test','feed-test']);
        const [v]=await query('INSERT INTO caseVersions (caseId, price) VALUES (?, ?)',[c.insertId,2000]);
        const [item]=await query('INSERT INTO caseItems (caseVersionId, name, price, rangeFrom, rangeTo) VALUES (?, ?, ?, ?, ?)',[v.insertId,'Feed prize',30000,0,99999]);
        for(const user of [human,bot]) {
            for(let i=0;i<16;i++) {
                await query('INSERT INTO caseOpenings (userId, caseVersionId, caseItemId) VALUES (?, ?, ?)',[user.id,v.insertId,item.insertId]);
                await query('INSERT INTO bets (userId, amount, winnings, game, completed) VALUES (?, ?, ?, ?, ?)',[user.id,2000,30000,'case',1]);
            }
        }
        const emitted=[];const chat=[];
        const io={to(){return this},except(){return this},emit(...args){emitted.push(args)}};
        const drops=loadRouteModule('routes/games/cases/functions.js',{
            '../../../socketio/server':io,'../../../database':{sql:{query}},
            '../../../utils/csgo/items':{getItemById:()=>null},'../../../socketio/chat/functions':{newMessage:m=>chat.push(m)}
        });
        await drops.cacheDrops();
        for(const type of ['all','top']) {
            assert.equal(drops.cachedDrops[type].length,15,'Filter bots before applying the feed limit');
            assert.ok(drops.cachedDrops[type].every(drop=>drop.user.id===human.id));
        }
        const results=[{item:{name:'Prize',price:30000}}];
        drops.newDrops(bot,{name:'Case'},results);
        assert.equal(emitted.length,0);assert.equal(chat.length,0);
        drops.newDrops(human,{name:'Case'},results);
        assert.equal(emitted.length,1);assert.equal(chat.length,1);
        assert.equal(emitted[0][1][0].user.id,human.id);
        emitted.length=0;
        const bets=loadRouteModule('socketio/bets.js',{
            './server':io,'../database':{sql:{query}},
            '../utils':{...routeUtils,mapUser:user=>({id:user.id,username:user.username})},
            './rain':{rains:{}},'../routes/admin/config':{sponsorLockedUsers:new Set()},'../routes/user/rakeback/functions':{cachedRakebacks:{}}
        });
        await bets.cacheBets();
        for(const type of ['all','high','lucky']) {
            const rows=await bets.getBets(type);assert.equal(rows.length,10);assert.ok(rows.every(bet=>bet.user.id===human.id));
        }
        emitted.length=0;
        await bets.newBets([{user:bot,amount:2000,payout:30000,game:'battle'},{user:human,amount:2000,payout:30000,game:'battle'}]);
        for(const event of emitted.filter(event=>event[0]==='bets')) assert.ok(event[2].every(bet=>bet.user.id===human.id));
        assert.equal((await query('SELECT COUNT(*) AS count FROM caseOpenings WHERE userId = ?',[bot.id]))[0][0].count,16,'Bot battle history remains intact');
    } finally {await db.query('ROLLBACK');}
});
