import {createResource, createSignal, For, Show} from "solid-js";
import {useNavigate} from "@solidjs/router";
import {authedAPI, createNotification} from "../../util/api";

let PROVABLY_CODE = {
    CASES: `const crypto = require('crypto');

const CHARSROLL = 15;
const MAXROLL = 100000;

const combine = (serverSeed, clientSeed, nonce) => {
    return crypto.createHmac('sha256', serverSeed).update(clientSeed + ':' + nonce).digest('hex');
}

const getResult = hashedValue => {
    const partHash = hashedValue.slice(0, CHARSROLL);
    const roll = parseInt(partHash, 16) % MAXROLL;
    return roll + 1;
};

console.log(getResult(combine(serverSeed, clientSeed, nonce)));`,

    BATTLES: `const crypto = require('crypto');

const CHARSROLL = 15;
const MAXROLL = 100000;

const combine = (serverSeed, clientSeed, nonce) => {
    return crypto.createHmac('sha256', serverSeed).update(clientSeed + ':' + nonce).digest('hex');
}

const getResult = hashedValue => {
    const partHash = hashedValue.slice(0, CHARSROLL);
    const roll = parseInt(partHash, 16) % MAXROLL;
    return roll + 1;
};

// CHANGE THESE VALUES
const unhashedServerSeed = ''; // shown at the end of the game
const clientSeed = ''; // eos blockchain transaction id
const slots = 2; // count of players in the battle
const rounds = 15; // amount of cases/rounds in the battle
// 

for (let i = 0; i < rounds; i++) {

    console.log('Round ' + (i + 1) + ' results:');

    for (let r = 0; r < slots; r++) {
        const nonce = i * slots + r;
        console.log('Player on seat ' + (r + 1) + ':, ' + getResult(combine(unhashedServerSeed, clientSeed, nonce)));
    }

}`,

    ROULETTE: `const crypto = require('crypto');

const clientSeed = "00000000000000000003e5a54c2898a18d262eb5860e696441f8a4ebbff03697";

const getResult = serverSeed => {

    const hmac = crypto.createHmac('sha256', serverSeed);
    hmac.update(clientSeed);
    const sha = hmac.digest('hex');

    const result = parseInt(sha.substr(0, 8), 16) % 15;
    return result;

};

console.log(getResult(serverSeed)); // roulette number between 0-14`,

    CRASH: `const crypto = require('crypto');

const clientSeed = "00000000000000000003e5a54c2898a18d262eb5860e696441f8a4ebbff03697";
const houseEdge = 10;

const getResult = serverSeed => {

    const hmac = crypto.createHmac('sha256', serverSeed);
    hmac.update(clientSeed);
    
    const sha = hmac.digest('hex');

    const hex = sha.substr(0, 8);
    const int = parseInt(hex, 16);

    const crashpoint = Math.max(1, (2 ** 32 / (int + 1)) * (1 - (houseEdge / 100)));
    return crashpoint;

};

console.log(getResult(serverSeed)); // round crashpoint`,

    COINFLIP: `const crypto = require('crypto');

const combine = (serverSeed, clientSeed) => {
    return crypto.createHmac('sha256', serverSeed).update(clientSeed).digest('hex');
}

const getResult = hashedValue => {
    const number = parseInt(hashedValue.charAt(1), 16);
    return (number % 2 === 0) ? 'ice' : 'fire'
};

console.log(getResult(combine(serverSeed, clientSeed))); // winning side`,

    MINES: `import _ from "lodash";
    
const floats = _.flatten(
  generateFloats(server_seed, client_seed, nonce, 0, mines)
).map((float: number, index: number) => float * (25 - index));

const minePositions = shuffle(
  [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
  floats
).slice(0, MINES);

console.log(floats);
console.log(minePositions);`,
}

const GAMES = [
    {
        key: 'CASES',
        label: 'Case Opening Fairness',
        seedsPanel: true,
        intro: 'The result for each case opening is determined by feeding the following variables into a SHA256 HMAC hashing algorithm:',
        bullets: [
            ['Server Seed', 'a 64 character string generated by the server and kept secret from you. The hash of this value is visible to you beforehand so that you can be sure we are not changing it. You can rotate the currently active value anytime from this page.'],
            ['Client Seed', 'a string generated by your browser which you can change anytime you want from this page.'],
            ['Nonce', 'a sequential number that increases with each case you open. It is specific to you and will not increase if you don\u2019t play.']
        ],
        paragraphs: [
            'You get the encrypted hash of the server seed before you open a case. Since you get it in advance, the site cannot change it later. It is encrypted, so you cannot calculate roll results in advance \u2014 only afterwards, once you rotate your seed and the unhashed value is revealed.',
            'Each case item gets an individual range of tickets according to its probability; the sum of all tickets is 100,000. To pick an item, we generate a number between 1-100,000 and find the item whose range contains it.',
            'Check out the code block below for details, or click the button to validate any of your openings externally.'
        ],
        code: 'CASES'
    },
    {
        key: 'BATTLES',
        label: 'Case Battles',
        seedsPanel: false,
        intro: 'Each battle opening is calculated with the following variables:',
        bullets: [
            ['Server Seed', 'a randomly generated hash, its SHA256 shown at battle creation.'],
            ['Client Seed', 'the ID of an EOS block we commit to before it is mined.'],
            ['Nonce', 'starts at 0 and increases by 1 on each opening.']
        ],
        paragraphs: [
            'At creation, a server seed is generated for each battle and its SHA256 hash is shown. After all players have joined and before the openings start, we commit to a future EOS block and use its ID as the client seed once mined.',
            'After the round is over the unhashed server seed is revealed so users can confirm its SHA256 matches the one shown previously. This way, neither the players nor our system know what data will be used to generate the results until after all players have committed their bets.'
        ],
        code: 'BATTLES'
    },
    {
        key: 'ROULETTE',
        label: 'Roulette',
        seedsPanel: false,
        intro: 'In Roulette, our system generates the result for each round using the SHA-256 hash of 2 inputs:',
        bullets: [
            ['Server Seed', 'a series of hashes generated from a genesis seed.'],
            ['Client Seed', 'the hash of Bitcoin block 788,500.']
        ],
        paragraphs: [
            'To calculate the Server Seed, we begin with a genesis seed and hash it using SHA-256, repeating the process to generate 10 million server seeds. The first game uses the 10 millionth seed, and each following game uses the next seed down the list.',
            '10 millionth server seed: acb0aa39d25f1a618ccf90cf695106c412759d07461a285dab94ac55c991aab4',
            'Client seed (Bitcoin block 788,500 hash): 00000000000000000003e5a54c2898a18d262eb5860e696441f8a4ebbff03697',
            'Players can replicate any past roll using the Node.js code below:'
        ],
        code: 'ROULETTE'
    },
    {
        key: 'CRASH',
        label: 'Crash',
        seedsPanel: false,
        intro: 'In Crash, our system generates the result for each round using the SHA-256 hash of 2 inputs:',
        bullets: [
            ['Server Seed', 'a series of hashes generated from a genesis seed.'],
            ['Client Seed', 'the hash of Bitcoin block 788,500.']
        ],
        paragraphs: [
            'To calculate the Server Seed, we begin with a genesis seed and hash it using SHA-256, repeating the process to generate 10 million server seeds. The first game uses the 10 millionth seed, and each following game uses the next seed down the list.',
            '10 millionth server seed: acb0aa39d25f1a618ccf90cf695106c412759d07461a285dab94ac55c991aab4',
            'Client seed (Bitcoin block 788,500 hash): 00000000000000000003e5a54c2898a18d262eb5860e696441f8a4ebbff03697',
            'Players can replicate any round crashpoint using the Node.js code below:'
        ],
        code: 'CRASH'
    },
    {
        key: 'COINFLIP',
        label: 'Coinflip',
        seedsPanel: false,
        intro: 'In Coinflip, our system generates the result for each game using the SHA-256 hash of 2 inputs:',
        bullets: [
            ['Server Seed', 'a randomly generated hash, its SHA256 shown at game creation.'],
            ['Client Seed', 'the ID of an EOS block we commit to before it is mined.']
        ],
        paragraphs: [
            'When a new coinflip game is created, we make a random server seed and show its SHA256 hash. After all players have placed their bets, we commit to a future block number on the EOS blockchain; once mined, its ID becomes the client seed.',
            'After the game is over the unhashed server seed is revealed so users can confirm its SHA256 matches the one shown previously. Players can replicate the winning side using the Node.js code below:'
        ],
        code: 'COINFLIP'
    },
    {
        key: 'MINES',
        label: 'Mines',
        seedsPanel: true,
        intro: 'In Mines, our system generates a 32-byte hexadecimal hash based on your server seed, client seed and nonce. The hash is converted into 4-byte parts used to generate floats between 0 and 1, which are multiplied by the remaining possible outcomes.',
        bullets: [
            ['Server Seed', 'a SHA-256 hash of 16 cryptographically secure random bytes. Can be rotated by you at any time.'],
            ['Client Seed', 'a seed that you can customize at any time.'],
            ['Nonce', 'the round number that increments with each bet.']
        ],
        paragraphs: [
            'For shuffling we use the Fisher\u2013Yates shuffle algorithm to ensure there are no duplicate outcomes \u2014 two mines can never occupy the same tile.',
            'A hashed version of your current server seed is available at any time on this page and can be rotated whenever you like. You can only unhash a game\u2019s server seed once it is no longer in use.'
        ],
        code: 'MINES'
    },
    {
        key: 'DAILY',
        label: 'Daily Cases',
        seedsPanel: true,
        intro: 'Daily case rewards use the same personal seed pair as regular case openings \u2014 your Server Seed, Client Seed and Nonce feed a SHA256 HMAC.',
        bullets: [
            ['Server Seed', 'your personal server seed \u2014 its hash is visible below and can be rotated anytime.'],
            ['Client Seed', 'your personal client seed, changeable anytime from this page.'],
            ['Nonce', 'increases with each opening tied to your seed pair.']
        ],
        paragraphs: [
            'Daily cases unlock by level and can be claimed once every 24 hours. The reward amounts per level tier are fixed and published on the rewards page, so there is no hidden roll \u2014 what you see is exactly what you get.',
            'Deposit-unlocked bonus cases use your seed pair with the standard case-opening algorithm below.'
        ],
        code: 'CASES'
    },
    {
        key: 'SUPERCHARGE',
        label: 'Supercharge Cases',
        seedsPanel: true,
        intro: 'Supercharge bonuses activate when you reach your deposit goal and follow fully deterministic rules.',
        bullets: [
            ['Activation', 'reaching the supercharge deposit goal activates a supercharge for a fixed duration.'],
            ['Bonus', 'the bonus amount is a fixed percentage of your qualifying deposit \u2014 no roll involved.'],
            ['Cases', 'supercharge case openings use your personal seed pair with the standard algorithm below.']
        ],
        paragraphs: [
            'Because the bonus amount is a deterministic function of your deposit, it can be verified directly: bonus = deposit \u00d7 5%.',
            'Any randomized supercharge case contents resolve through the same provably fair SHA256 HMAC pipeline as regular cases.'
        ],
        code: 'CASES'
    }
]

const CATEGORY_ICONS = {
    CASES: 'M4 7h16v3h-1v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9H4V7zm3 3v8h10v-8H7zm-1-7h12l1 3H5l1-3z',
    BATTLES: 'M4 4l7 7-2 2-7-7V4h2zm16 0v2l-7 7 2 2 7-7V4h-2zM7 15l2 2-3 3H4v-2l3-3zm10 0l3 3v2h-2l-3-3 2-2z',
    ROULETTE: 'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 4a6 6 0 1 1 0 12 6 6 0 0 1 0-12zm0 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6z',
    CRASH: 'M13 3c4 0 8 4 8 8l-4 1-5-5 1-4zm-2 4l6 6-2 6-4 2-2-4-4-2 2-4 4-4zM5 17l2 2-3 3H2v-2l3-3z',
    COINFLIP: 'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 4a6 6 0 1 1 0 12 6 6 0 0 1 0-12z',
    MINES: 'M15 4l2 2 2-2 1 1-2 2 2 2-1 1-2-2-1 1a8 8 0 1 1-3-3l1-1-1-1 2-2zM10 20a6 6 0 1 0 0-12 6 6 0 0 0 0 12z',
    DAILY: 'M4 8h16v4h-1v8H5v-8H4V8zm7 4v8h2v-8h-2zm1-10c2 0 3 1 3 3H9c0-2 1-3 3-3zM6 5h4v3H6a1.5 1.5 0 1 1 0-3zm12 0a1.5 1.5 0 1 1 0 3h-4V5h4z',
    SUPERCHARGE: 'M13 2L4 13h5v9l9-11h-5l0-9z'
}

function Provably(props) {

    const navigate = useNavigate()
    const [selected, setSelected] = createSignal(null)
    const [seeds, {mutate: mutateSeeds}] = createResource(fetchSeeds)

    async function fetchSeeds() {
        try {
            let res = await authedAPI('/fairness/seeds', 'GET', null)
            return res?.success ? res : null
        } catch (e) {
            return null
        }
    }

    function game() {
        return GAMES.find((g) => g.key === selected()) || GAMES[0]
    }

    function copy(text) {
        navigator.clipboard.writeText(text || '')
        createNotification('success', 'Copied to clipboard.')
    }

    async function rotateClientSeed() {
        const newSeed = Array.from(crypto.getRandomValues(new Uint8Array(16))).map((b) => b.toString(16).padStart(2, '0')).join('').slice(0, 24)
        let res = await authedAPI('/fairness/seeds/client', 'POST', JSON.stringify({seed: newSeed}), true)
        if (res?.success) {
            mutateSeeds({...seeds(), clientSeed: res.clientSeed})
            createNotification('success', 'Your client seed has been changed.')
        }
    }

    async function rotateServerSeed() {
        let res = await authedAPI('/fairness/seeds/rotate', 'POST', null, true)
        if (res?.success) {
            mutateSeeds({...seeds(), serverSeedHash: res.serverSeedHash, nonce: res.nonce})
            copy(res.revealedServerSeed)
            createNotification('success', 'Server seed rotated \u2014 your previous unhashed seed was copied to your clipboard.')
        }
    }

    function highlightLine(line) {
        const regex = /(\/\/.*$)|('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|`(?:[^`\\]|\\.)*`)|\b(const|let|var|function|async|await|return|for|of|in|if|else|new|import|from|require|console)\b|\b(\d[\w.]*)\b/g
        const parts = []
        let last = 0
        let m
        while ((m = regex.exec(line)) !== null) {
            if (m.index > last) parts.push(line.slice(last, m.index))
            if (m[1] !== undefined) parts.push(<span class='tok-comment'>{m[1]}</span>)
            else if (m[2] !== undefined) parts.push(<span class='tok-string'>{m[2]}</span>)
            else if (m[3] !== undefined) parts.push(<span class='tok-keyword'>{m[3]}</span>)
            else parts.push(<span class='tok-number'>{m[4]}</span>)
            last = m.index + m[0].length
        }
        if (last < line.length) parts.push(line.slice(last))
        return parts
    }

    function SeedControls() {
        const hasSeeds = !!seeds()

        return (
            <div class='seeds-row'>
                <div class='seed-group'>
                    <p class='seed-label'>Client Seed</p>
                    <div class='seed-field'>
                        <p class='seed-value'>{seeds()?.clientSeed || 'Sign in to view and reroll your seed'}</p>
                        <button class='icon-btn' title='Copy client seed' onClick={() => copy(seeds()?.clientSeed)} disabled={!hasSeeds}>
                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="14" viewBox="0 0 14 16" fill="currentColor">
                                <path d="M8.62259 2.2981H1.52163C0.681259 2.2981 0 2.97936 0 3.81974V13.964C0 14.8043 0.681259 15.4856 1.52163 15.4856H8.62259C9.46297 15.4856 10.1442 14.8043 10.1442 13.964V3.81974C10.1442 2.97936 9.46297 2.2981 8.62259 2.2981Z"/>
                                <path d="M13.1876 1.79089V11.9351C13.1864 12.3383 13.0257 12.7246 12.7406 13.0097C12.4555 13.2948 12.0692 13.4555 11.666 13.4567H11.1588V3.81974C11.1588 3.14713 10.8916 2.50208 10.416 2.02647C9.94036 1.55087 9.2953 1.28368 8.6227 1.28368H3.13467C3.23932 0.987696 3.43295 0.731325 3.68902 0.549713C3.9451 0.368101 4.25107 0.270139 4.56501 0.269257H11.666C12.0692 0.270461 12.4555 0.431162 12.7406 0.716263C13.0257 1.00136 13.1864 1.3877 13.1876 1.79089Z"/>
                            </svg>
                        </button>
                    </div>
                </div>
                <button class='rotate-btn' title='Reroll client seed' onClick={rotateClientSeed} disabled={!hasSeeds}>
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 4V1L8 5L12 9V6C15.31 6 18 8.69 18 12C18 13.01 17.75 13.97 17.3 14.8L18.76 16.26C19.54 15.03 20 13.57 20 12C20 7.58 16.42 4 12 4ZM12 18C8.69 18 6 15.31 6 12C6 10.99 6.25 10.03 6.7 9.2L5.24 7.74C4.46 8.97 4 10.43 4 12C4 16.42 7.58 20 12 20V23L16 19L12 15V18Z"/>
                    </svg>
                </button>

                <div class='seed-group'>
                    <p class='seed-label'>Server Hash</p>
                    <div class='seed-field'>
                        <p class='seed-value'>{seeds()?.serverSeedHash || 'Sign in to view and reroll your seed'}</p>
                        <button class='icon-btn' title='Copy server hash' onClick={() => copy(seeds()?.serverSeedHash)} disabled={!hasSeeds}>
                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="14" viewBox="0 0 14 16" fill="currentColor">
                                <path d="M8.62259 2.2981H1.52163C0.681259 2.2981 0 2.97936 0 3.81974V13.964C0 14.8043 0.681259 15.4856 1.52163 15.4856H8.62259C9.46297 15.4856 10.1442 14.8043 10.1442 13.964V3.81974C10.1442 2.97936 9.46297 2.2981 8.62259 2.2981Z"/>
                                <path d="M13.1876 1.79089V11.9351C13.1864 12.3383 13.0257 12.7246 12.7406 13.0097C12.4555 13.2948 12.0692 13.4555 11.666 13.4567H11.1588V3.81974C11.1588 3.14713 10.8916 2.50208 10.416 2.02647C9.94036 1.55087 9.2953 1.28368 8.6227 1.28368H3.13467C3.23932 0.987696 3.43295 0.731325 3.68902 0.549713C3.9451 0.368101 4.25107 0.270139 4.56501 0.269257H11.666C12.0692 0.270461 12.4555 0.431162 12.7406 0.716263C13.0257 1.00136 13.1864 1.3877 13.1876 1.79089Z"/>
                            </svg>
                        </button>
                    </div>
                </div>
                <button class='rotate-btn' title='Reroll server seed' onClick={rotateServerSeed} disabled={!hasSeeds}>
                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 4V1L8 5L12 9V6C15.31 6 18 8.69 18 12C18 13.01 17.75 13.97 17.3 14.8L18.76 16.26C19.54 15.03 20 13.57 20 12C20 7.58 16.42 4 12 4ZM12 18C8.69 18 6 15.31 6 12C6 10.99 6.25 10.03 6.7 9.2L5.24 7.74C4.46 8.97 4 10.43 4 12C4 16.42 7.58 20 12 20V23L16 19L12 15V18Z"/>
                    </svg>
                </button>

                <div class='seed-group counter'>
                    <p class='seed-label'>Counter</p>
                    <div class='seed-field'>
                        <p class='seed-value'>{seeds()?.nonce ?? '-'}</p>
                    </div>
                </div>
            </div>
        )
    }

    return (
        <>
            <div class='fairness-container fadein'>

                <Show when={!selected()}>
                    <div class='category-grid'>
                        <For each={GAMES}>
                            {(g) => (
                                <button class='category-card' onClick={() => setSelected(g.key)}>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none">
                                        <path d={CATEGORY_ICONS[g.key]} fill="#1fd65f"/>
                                    </svg>
                                    <div class='category-info'>
                                        <p class='category-title'>{g.label}</p>
                                        <p class='category-sub'>Game Fairness</p>
                                    </div>
                                </button>
                            )}
                        </For>
                    </div>
                </Show>

                <Show when={selected()}>
                <div class='topbar'>
                    <div class='tabs'>
                        <button class='tab active'>{game().label} Fairness</button>
                    </div>

                    <button class='back-btn' onClick={() => setSelected(null)}>
                        <svg xmlns="http://www.w3.org/2000/svg" width="7" height="11" viewBox="0 0 7 11" fill="none">
                            <path d="M6 1L1.5 5.5L6 10" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        Back
                    </button>
                </div>

                <SeedControls/>

                <h2 class='section-heading'>TECHNICAL DETAILS</h2>

                <p class='text'>{game().intro}</p>

                <For each={game().bullets}>
                    {([term, text]) => (
                        <p class='text'><span class='term'>{term}</span> {text}</p>
                    )}
                </For>

                <For each={game().paragraphs}>
                    {(text) => <p class='text'>{text}</p>}
                </For>

                <div class='actions-row'>
                    <a class='validate-btn' href='https://runkit.com/new' target='_blank' rel='noreferrer'>Validate Result Externally</a>
                </div>

                <div class='code-panel'>
                    <For each={PROVABLY_CODE[game().code].split('\n')}>
                        {(line, index) => (
                            <div class='code-line'>
                                <span class='line-number'>{index() + 1}</span>
                                <span class='line-content'>{highlightLine(line)}</span>
                            </div>
                        )}
                    </For>
                </div>
                </Show>
            </div>

            <style jsx>{`
              .fairness-container {
                width: 100%;
                max-width: 1400px;
                height: fit-content;

                box-sizing: border-box;
                padding: 30px 0;
                margin: 0 auto;

                display: flex;
                flex-direction: column;
                gap: 14px;
              }

              .topbar {
                display: flex;
                align-items: flex-start;
                justify-content: space-between;
                gap: 12px;
                margin-bottom: 10px;
              }

              .category-grid {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
                gap: 12px;
              }

              .category-card {
                display: flex;
                align-items: center;
                gap: 14px;

                padding: 16px;
                outline: unset;
                border-radius: 8px;
                background: linear-gradient(145deg, rgba(51, 61, 79, 0.62) 0%, rgba(22, 29, 39, 0.8) 100%);
                border: 1px solid rgba(131, 147, 168, 0.25);
                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.06);
                backdrop-filter: blur(12px) saturate(125%);

                cursor: pointer;
                text-align: left;
                transition: border-color .2s, background-color .2s, transform .2s;
              }

              .category-card:hover {
                border-color: rgba(31, 214, 95, 0.42);
                background: linear-gradient(145deg, rgba(58, 72, 92, 0.7) 0%, rgba(24, 34, 46, 0.86) 100%);
                transform: translateY(-1px);
              }

              .category-info {
                display: flex;
                flex-direction: column;
                gap: 2px;
                min-width: 0;
              }

              .category-title {
                color: #FFF;
                font-family: "Geogrotesque Wide", sans-serif;
                font-size: 13px;
                font-weight: 700;
              }

              .category-sub {
                color: #8b92a0;
                font-size: 12px;
                font-weight: 600;
              }

              .tabs {
                display: flex;
                flex-wrap: wrap;
                gap: 8px;
              }

              .tab {
                height: 34px;
                padding: 0 14px;

                outline: unset;
                border-radius: 7px;
                background: linear-gradient(145deg, rgba(44, 52, 67, 0.62) 0%, rgba(23, 29, 39, 0.76) 100%);
                border: 1px solid rgba(131, 147, 168, 0.24);
                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

                color: #8b92a0;
                font-family: "Geogrotesque Wide", sans-serif;
                font-size: 12px;
                font-weight: 700;

                cursor: pointer;
                                transition: color .2s, border-color .2s, background-color .2s;
              }

              .tab:hover {
                color: #FFF;
                                border-color: rgba(31, 214, 95, 0.35);
              }

              .tab.active {
                color: #FFF;
                                background: linear-gradient(145deg, rgba(49, 69, 57, 0.56) 0%, rgba(19, 30, 26, 0.8) 100%);
                                border-color: rgba(31, 214, 95, 0.56);
                                box-shadow: inset 0 1px 0 rgba(162, 237, 192, 0.28);
              }

              .back-btn {
                display: flex;
                align-items: center;
                gap: 8px;

                height: 34px;
                padding: 0 16px;

                outline: unset;
                border-radius: 7px;
                background: linear-gradient(145deg, rgba(44, 52, 67, 0.62) 0%, rgba(23, 29, 39, 0.76) 100%);
                border: 1px solid rgba(131, 147, 168, 0.24);
                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

                color: #FFF;
                font-family: "Geogrotesque Wide", sans-serif;
                font-size: 12px;
                font-weight: 700;

                cursor: pointer;
                white-space: nowrap;
                                transition: border-color .2s, color .2s;
                            }

                            .back-btn:hover {
                                color: #edf6ff;
                                border-color: rgba(31, 214, 95, 0.35);
              }

              .section-heading {
                margin: 6px 0 0 0;

                color: #1fd65f;
                font-family: "Geogrotesque Wide", sans-serif;
                font-size: 15px;
                font-weight: 700;
                letter-spacing: 0.04em;
              }

              .text {
                color: #aeb6c5;
                font-size: 13px;
                font-weight: 500;
                line-height: 1.55;
              }

              .term {
                color: #FFF;
                font-weight: 700;
              }

              .actions-row {
                margin: 6px 0;
              }

              .validate-btn {
                display: inline-flex;
                align-items: center;

                height: 36px;
                padding: 0 16px;

                border-radius: 7px;
                background: linear-gradient(145deg, rgba(44, 52, 67, 0.62) 0%, rgba(23, 29, 39, 0.76) 100%);
                border: 1px solid rgba(131, 147, 168, 0.24);
                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

                color: #FFF;
                font-family: "Geogrotesque Wide", sans-serif;
                font-size: 12px;
                font-weight: 700;
                text-decoration: none;

                cursor: pointer;
                transition: border-color .2s, color .2s;
              }

              .validate-btn:hover {
                color: #edf6ff;
                border-color: rgba(31, 214, 95, 0.45);
              }

              .seeds-row {
                display: flex;
                align-items: flex-end;
                gap: 8px;
                flex-wrap: wrap;
              }

              .seed-group {
                flex: 1 1 260px;
                min-width: 0;
                display: flex;
                flex-direction: column;
                gap: 5px;
              }

              .seed-group.counter {
                flex: 0 1 180px;
              }

              .seed-label {
                color: #8b92a0;
                font-size: 11px;
                font-weight: 700;
              }

              .seed-field {
                display: flex;
                align-items: center;
                gap: 8px;

                height: 42px;
                padding: 0 12px;

                border-radius: 7px;
                background: linear-gradient(145deg, rgba(26, 31, 41, 0.72) 0%, rgba(13, 18, 24, 0.86) 100%);
                border: 1px solid rgba(131, 147, 168, 0.22);
                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);
              }

              .seed-value {
                flex: 1;
                min-width: 0;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;

                color: #FFF;
                font-family: monospace;
                font-size: 12px;
                font-weight: 600;
              }

              .icon-btn, .rotate-btn {
                outline: unset;
                border: unset;
                background: unset;

                color: #8b92a0;
                cursor: pointer;
                transition: all .2s;

                display: flex;
                align-items: center;
                justify-content: center;
              }

                            .icon-btn:disabled, .rotate-btn:disabled {
                                opacity: 0.45;
                                cursor: not-allowed;
                            }

              .icon-btn:hover, .rotate-btn:hover {
                color: #1fd65f;
              }

                            .icon-btn:disabled:hover, .rotate-btn:disabled:hover {
                                color: #8b92a0;
                            }

              .rotate-btn {
                width: 42px;
                height: 42px;

                                border-radius: 7px;
                                background: linear-gradient(145deg, rgba(44, 52, 67, 0.62) 0%, rgba(23, 29, 39, 0.76) 100%);
                                border: 1px solid rgba(131, 147, 168, 0.24);
                                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);
              }

              .code-panel {
                border-radius: 8px;
                                background: linear-gradient(145deg, rgba(26, 31, 41, 0.72) 0%, rgba(13, 18, 24, 0.86) 100%);
                                border: 1px solid rgba(131, 147, 168, 0.22);
                                box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);
                padding: 18px 0;
                margin-top: 6px;

                overflow-x: auto;
                font-family: monospace;
                font-size: 12.5px;
                line-height: 1.6;
              }

              .code-line {
                display: flex;
                white-space: pre;
              }

              .line-number {
                width: 46px;
                min-width: 46px;
                padding-right: 14px;
                text-align: right;

                color: #4a5261;
                user-select: none;
              }

              .line-content {
                color: #d7dde8;
              }

              .line-content :global(.tok-keyword) {
                                color: #7de5ac;
              }

              .line-content :global(.tok-string) {
                color: #ffb13e;
              }

              .line-content :global(.tok-comment) {
                color: #56607a;
                font-style: italic;
              }

              .line-content :global(.tok-number) {
                color: #f78c6c;
              }

              @media only screen and (max-width: 1000px) {
                .fairness-container {
                  padding-bottom: 90px;
                }

                .topbar {
                  flex-direction: column-reverse;
                }
              }
            `}</style>
        </>
    );
}

export default Provably;

