-- Runtime additions missing from the legacy MySQL base schema.
-- Applied after the generated schema when bootstrapping a fresh Neon database.
ALTER TABLE users ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "deletedBy" BIGINT;
ALTER TABLE "discordAuths" ALTER COLUMN id SET DEFAULT replace(gen_random_uuid()::text, '-', '');
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS ip VARCHAR(64);
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS "refreshToken" TEXT;
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS "transactionId" VARCHAR(255);
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS ip VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS surveys_provider_transaction ON surveys (provider, "transactionId");
ALTER TABLE "cardDeposits" ADD COLUMN IF NOT EXISTS "orderId" VARCHAR(255);
ALTER TABLE "cardDeposits" ADD COLUMN IF NOT EXISTS "coinAmount" DECIMAL(20,2) NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS card_deposits_order ON "cardDeposits" ("orderId");

CREATE TABLE IF NOT EXISTS tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fromUserId" BIGINT NOT NULL,
    "toUserId" BIGINT NOT NULL,
    amount DECIMAL(20,2) NOT NULL CHECK (amount >= 0),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS tips_users ON tips ("fromUserId", "toUserId");

CREATE TABLE IF NOT EXISTS "hacksawSessions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sessionId" VARCHAR(255) NOT NULL UNIQUE,
    "gameId" VARCHAR(128) NOT NULL,
    "hacksawId" VARCHAR(255) NOT NULL,
    "bonusGames" TEXT NOT NULL DEFAULT '[]',
    "userId" BIGINT NOT NULL,
    "defaultBalance" DECIMAL(20,2) NOT NULL DEFAULT 0,
    balance DECIMAL(20,2) NOT NULL DEFAULT 0,
    ended SMALLINT NOT NULL DEFAULT 0 CHECK (ended IN (0, 1)),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS hacksaw_sessions_user_game ON "hacksawSessions" ("userId", "gameId", ended);

CREATE TABLE IF NOT EXISTS "slotsSpins" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    "providerSpinId" VARCHAR(255) NOT NULL,
    "betInfo" TEXT,
    "userId" BIGINT NOT NULL,
    "sessionId" BIGINT NOT NULL,
    "slotId" BIGINT NOT NULL,
    amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    payout DECIMAL(20,2) NOT NULL DEFAULT 0,
    status VARCHAR(64) NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, "providerSpinId")
);
CREATE INDEX IF NOT EXISTS slots_spins_session ON "slotsSpins" ("sessionId", status);
