// Compatibility for the MySQL query forms used by this application. Values
// remain parameters; SQL literals/comments are never rewritten as SQL code.
const fs = require('node:fs');
const path = require('node:path');

function protect(sql) {
    const literals = [];
    const code = sql.replace(/'(?:\\.|''|[^'\\])*'|"(?:\\.|""|[^"\\])*"|--[^\r\n]*|\/\*[\s\S]*?\*\//g, token => {
        if (token.startsWith('--') || token.startsWith('/*')) return ' ';
        const quote = token[0];
        let value = token.slice(1, -1).replaceAll(quote + quote, quote);
        value = value.replace(/\\([\s\S])/g, (_, c) => ({ n: '\n', r: '\r', t: '\t', '0': '\0' })[c] ?? c);
        literals.push("'" + value.replaceAll("'", "''") + "'");
        return `\x01${literals.length - 1}\x02`;
    });
    return { code, restore: value => value.replace(/\x01(\d+)\x02/g, (_, i) => literals[i]) };
}

function splitTopLevel(code, separator = ',') {
    const parts = [];
    let depth = 0;
    let start = 0;
    for (let i = 0; i < code.length; i++) {
        if (code[i] === '(') depth++;
        if (code[i] === ')') depth--;
        if (code[i] === separator && depth === 0) {
            parts.push(code.slice(start, i).trim());
            start = i + 1;
        }
    }
    parts.push(code.slice(start).trim());
    return parts.filter(Boolean);
}

function quoteIdentifiers(code) {
    code = code.replace(/(?<!`)\b2fa\b(?!`)/g, '`2fa`');
    return code.replace(/`([^`]+)`|\b[a-zA-Z_][\w]*\b/g, (token, quoted) => {
        if (quoted) return '"' + quoted.replaceAll('"', '""') + '"';
        return /[a-z]/.test(token) && /[A-Z]/.test(token) ? `"${token}"` : token;
    });
}

function convertColumn(definition) {
    const column = definition.match(/^(`[^`]+`|\w+)\s+/)?.[1];
    if (!column) throw new Error('Unsupported PostgreSQL column definition');
    const unsigned = /\bUNSIGNED\b/i.test(definition);
    const enumeration = definition.match(/\bENUM\(([^)]*)\)/i);
    const updated = /\bON UPDATE CURRENT_TIMESTAMP\b/i.test(definition);
    let sql = definition
        .replace(/\bENUM\([^)]*\)/gi, 'TEXT')
        .replace(/\b(?:TINYINT|SMALLINT)(?:\(\d+\))?/gi, 'SMALLINT')
        .replace(/\b(?:INT|INTEGER)(?:\(\d+\))?\s+UNSIGNED\b/gi, 'BIGINT')
        .replace(/\bUNSIGNED\b/gi, '')
        .replace(/\b(?:DATETIME|TIMESTAMP)\b/gi, 'TIMESTAMPTZ')
        .replace(/\b(?:LONGTEXT|MEDIUMTEXT)\b/gi, 'TEXT')
        .replace(/\bAUTO_INCREMENT\b/gi, 'GENERATED BY DEFAULT AS IDENTITY')
        .replace(/\bON UPDATE CURRENT_TIMESTAMP\b/gi, '')
        .replace(/\s+AFTER\s+`?\w+`?\s*$/i, '');
    if (unsigned) sql += ` CHECK (${column} >= 0)`;
    if (enumeration) sql += ` CHECK (${column} IN (${enumeration[1]}))`;
    return { sql, updated, column };
}

function convertCreateTable(sql) {
    const { code, restore } = protect(sql);
    const match = code.trim().match(/^CREATE TABLE(?: IF NOT EXISTS)?\s+(`?\w+`?)\s*\(([\s\S]*)\)\s*(?:ENGINE[^;]*)?;?$/i);
    if (!match) throw new Error('Unsupported PostgreSQL CREATE TABLE statement');
    const [, table, body] = match;
    const columns = [];
    const indexes = [];
    const updatedColumns = [];
    for (const definition of splitTopLevel(body)) {
        const index = definition.match(/^(UNIQUE\s+)?KEY\s+(`?\w+`?)\s*\((.*)\)$/i);
        if (index) {
            if (index[1]) columns.push(`CONSTRAINT ${index[2]} UNIQUE (${index[3]})`);
            else indexes.push(`CREATE INDEX IF NOT EXISTS ${index[2]} ON ${table} (${index[3]})`);
        } else if (/^(?:PRIMARY KEY|CONSTRAINT|FOREIGN KEY|CHECK)\b/i.test(definition)) {
            columns.push(definition);
        } else {
            const converted = convertColumn(definition);
            columns.push(converted.sql);
            if (converted.updated) updatedColumns.push(converted.column);
        }
    }
    const statements = [`CREATE TABLE IF NOT EXISTS ${table} (\n    ${columns.join(',\n    ')}\n)`, ...indexes];
    if (updatedColumns.length) {
        const functionName = `touch_${table.replaceAll('`', '')}`;
        statements.push(`CREATE OR REPLACE FUNCTION ${functionName}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN ${updatedColumns.map(column => `NEW.${column} = CURRENT_TIMESTAMP;`).join(' ')} RETURN NEW; END $$`);
        statements.push(`DROP TRIGGER IF EXISTS touch_timestamp ON ${table}`);
        statements.push(`CREATE TRIGGER touch_timestamp BEFORE UPDATE ON ${table} FOR EACH ROW EXECUTE FUNCTION ${functionName}()`);
    }
    return statements.map(statement => restore(quoteIdentifiers(statement)));
}

const schemaSource = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
const tableKeys = new Map();
for (const match of schemaSource.matchAll(/CREATE TABLE IF NOT EXISTS `([^`]+)`\s*\(([\s\S]*?)\) ENGINE/g)) {
    const primary = match[2].match(/PRIMARY KEY\s*\(([^)]+)\)/i);
    tableKeys.set(match[1], primary ? primary[1].replaceAll('`', '').split(',').map(s => s.trim()) : []);
}
for (const table of ['tips', 'hacksawSessions', 'slotsSpins']) tableKeys.set(table, ['id']);

function rewriteFunctions(code) {
    code = code.replace(/\bCURDATE\(\)/gi, 'CURRENT_DATE');
    // Resolve innermost date expressions first, including nested dashboard dates.
    code = code.replace(/WEEKDAY\(([^()]*)\)/gi, '(EXTRACT(ISODOW FROM $1) - 1)');
    // Balanced scanning avoids truncating NOW() and nested DATE_SUB calls.
    const call = /\b(DATE_SUB|DATE_ADD|DATE_FORMAT|UNIX_TIMESTAMP|FROM_UNIXTIME)\s*\(/i.exec(code);
    if (!call) return code.replace(/\bINTERVAL\s+(\d+)\s+(SECOND|MINUTE|HOUR|DAY|WEEK|MONTH|YEAR)\b/gi, "INTERVAL '$1 $2'");
    const open = call.index + call[0].length - 1;
    let depth = 1;
    let end = open + 1;
    while (end < code.length && depth) {
        if (code[end] === '(') depth++;
        if (code[end] === ')') depth--;
        end++;
    }
    if (depth) throw new Error('Unbalanced SQL function');
    const args = splitTopLevel(code.slice(open + 1, end - 1));
    const name = call[1].toUpperCase();
    let result;
    if (name === 'DATE_SUB' || name === 'DATE_ADD') {
        const interval = args[1]?.match(/^INTERVAL\s+([\s\S]+)\s+(SECOND|MINUTE|HOUR|DAY|WEEK|MONTH|YEAR)$/i);
        if (!interval) throw new Error('Unsupported date interval');
        result = `(${rewriteFunctions(args[0])} ${name === 'DATE_ADD' ? '+' : '-'} ((${rewriteFunctions(interval[1])}) * INTERVAL '1 ${interval[2]}'))`;
    } else if (name === 'FROM_UNIXTIME') result = `TO_TIMESTAMP(${rewriteFunctions(args[0])})`;
    else if (name === 'UNIX_TIMESTAMP') result = `EXTRACT(EPOCH FROM ${rewriteFunctions(args[0] || 'NOW()')})`;
    else result = `TO_CHAR(${rewriteFunctions(args[0])}, ${args[1]})`;
    return code.slice(0, call.index) + result + rewriteFunctions(code.slice(end));
}

function compileQuery(sql, params = []) {
    const { code: protectedCode, restore } = protect(sql);
    let code = protectedCode.trim().replace(/;\s*$/, '');
    if (code.includes(';')) throw new Error('Only one application SQL statement is allowed per query');
    if (!Array.isArray(params)) params = [params];
    const values = [];
    let paramIndex = 0;
    const bind = value => {
        if (value === undefined) throw new Error('Undefined SQL parameter');
        if (typeof value === 'boolean') value = Number(value);
        if (value && typeof value === 'object' && !(value instanceof Date) && !Buffer.isBuffer(value)) value = JSON.stringify(value);
        values.push(value);
        return `$${values.length}`;
    };
    code = code.replace(/\?/g, (placeholder, offset) => {
        if (paramIndex >= params.length) throw new Error('Missing SQL parameter');
        const value = params[paramIndex++];
        if (!Array.isArray(value)) return bind(value);
        if (value.some(Array.isArray)) {
            if (!value.every(row => Array.isArray(row) && row.length === value[0].length && row.length)) throw new Error('Invalid bulk insert rows');
            if (!/\bVALUES\s*$/i.test(protectedCode.trim().slice(0, offset))) throw new Error('Bulk rows require VALUES ?');
            return value.map(row => `(${row.map(bind).join(', ')})`).join(', ');
        }
        if (!value.length) return '__EMPTY_SET__';
        return value.map(bind).join(', ');
    });
    if (paramIndex !== params.length) throw new Error('Too many SQL parameters');
    code = code.replace(/(?:`?\w+`?\.)?`?\w+`?\s+(NOT\s+)?IN\s*\(\s*__EMPTY_SET__\s*\)/gi, (_, negated) => negated ? 'TRUE' : 'FALSE');
    if (code.includes('__EMPTY_SET__')) throw new Error('Empty arrays are only supported in IN predicates');

    const insert = code.match(/^INSERT(?: IGNORE)? INTO\s+`?(\w+)`?/i);
    const ignore = /^INSERT IGNORE\b/i.test(code);
    code = code.replace(/^INSERT IGNORE\b/i, 'INSERT');
    const duplicate = code.match(/\s+ON DUPLICATE KEY UPDATE\s+([\s\S]+)$/i);
    if (duplicate) {
        const key = tableKeys.get(insert?.[1]);
        if (!key?.length) throw new Error('No PostgreSQL conflict key configured for this table');
        let update = duplicate[1].replace(/\bVALUES\((`?\w+`?)\)/gi, 'EXCLUDED.$1');
        update = update.replace(/(`?\w+`?)\s*=\s*\1\b/g, '$1 = EXCLUDED.$1');
        code = code.slice(0, duplicate.index) + ` ON CONFLICT (${key.map(k => '`' + k + '`').join(', ')}) DO UPDATE SET ${update}`;
    } else if (ignore) code += ' ON CONFLICT DO NOTHING';

    code = rewriteFunctions(code);
    code = code.replace(/(\$\d+)(\s+IS\s+(?:NOT\s+)?NULL\b)/gi, '$1::text$2');
    if (/^ALTER TABLE\b/i.test(code)) {
        const match = code.match(/^(ALTER TABLE\s+`?\w+`?\s+ADD COLUMN(?: IF NOT EXISTS)?\s+)([\s\S]+)$/i);
        if (!match) throw new Error('Use PostgreSQL migrations for this ALTER TABLE statement');
        code = match[1] + convertColumn(match[2]).sql;
    }
    // Returning only the ID preserves the mysql2 result shape without returning
    // entire user/payment rows. Tables with composite keys do not have insertId.
    if (insert && tableKeys.get(insert[1])?.includes('id')) code += ' RETURNING id';
    let text = restore(quoteIdentifiers(code));
    if (/\bTO_CHAR\(/i.test(code)) text = text.replace(/'%d\/%m\/%Y'/g, "'DD/MM/YYYY'");
    return { text, values };
}

function buildSchema() {
    const { code, restore } = protect(schemaSource);
    const statements = [];
    for (const part of splitTopLevel(code, ';')) {
        const sql = restore(part);
        if (/^CREATE TABLE/i.test(part)) statements.push(...convertCreateTable(sql));
        else if (/^INSERT /i.test(part)) statements.push(compileQuery(sql).text.replace(/ RETURNING id$/, ''));
        else if (!/^(SET|PREPARE|EXECUTE|DEALLOCATE)\b/i.test(part)) throw new Error('Unrecognized schema statement');
    }
    // Columns required by runtime queries but absent from the legacy base schema.
    statements.push(
        'ALTER TABLE roulette ADD COLUMN IF NOT EXISTS "serverSeed" VARCHAR(255)',
        'ALTER TABLE "fairRolls" ADD COLUMN IF NOT EXISTS "serverSeed" VARCHAR(255) NOT NULL DEFAULT \'\'',
        'ALTER TABLE "fairRolls" ADD COLUMN IF NOT EXISTS "clientSeed" VARCHAR(255) NOT NULL DEFAULT \'\'',
        'ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "discordId" VARCHAR(32)',
        'ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS token VARCHAR(512)',
        'ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMPTZ',
        'ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "refreshToken" VARCHAR(512)'
    );
    return statements.join(';\n\n') + ';\n\n' + fs.readFileSync(path.join(__dirname, 'postgres-runtime.sql'), 'utf8');
}

module.exports = { compileQuery, convertCreateTable, buildSchema };
