-- Generated by npm run db:neon:schema from database/schema.sql.
CREATE TABLE IF NOT EXISTS "announcements" (
    "id"          BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "message"     VARCHAR(500)    NOT NULL,
    "type"        TEXT NOT NULL DEFAULT 'info' CHECK ("type" IN ('info','success','warning','error')),
    "link"        VARCHAR(500)    DEFAULT NULL,
    "linkText"    VARCHAR(100)    DEFAULT NULL,
    "active"      SMALLINT      NOT NULL DEFAULT 1,
    "dismissible" SMALLINT      NOT NULL DEFAULT 0,
    "priority"    SMALLINT  NOT NULL DEFAULT 0 CHECK ("priority" >= 0),
    "startsAt"    TIMESTAMPTZ        DEFAULT NULL,
    "expiresAt"   TIMESTAMPTZ        DEFAULT NULL,
    "createdBy"   BIGINT  DEFAULT NULL CHECK ("createdBy" >= 0),
    "createdAt"   TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE OR REPLACE FUNCTION touch_announcements() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."updatedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "announcements";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "announcements" FOR EACH ROW EXECUTE FUNCTION touch_announcements();

CREATE TABLE IF NOT EXISTS "homeSlides" (
    "id"              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "title"           VARCHAR(120) NOT NULL,
    "subtitle"        VARCHAR(180) DEFAULT NULL,
    "cta"             VARCHAR(60)  DEFAULT NULL,
    "href"            VARCHAR(500) DEFAULT NULL,
    "tag"             VARCHAR(80)  DEFAULT NULL,
    "accentColor"     VARCHAR(24)  NOT NULL DEFAULT '#1fd65f',
    "image"           VARCHAR(512) DEFAULT NULL,
    "backgroundImage" VARCHAR(512) DEFAULT NULL,
    "active"          SMALLINT   NOT NULL DEFAULT 1,
    "sortOrder"       INT          NOT NULL DEFAULT 0,
    "createdAt"       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"       TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_homeSlides_active_sort" ON "homeSlides" ("active", "sortOrder");

CREATE OR REPLACE FUNCTION "touch_homeSlides"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."updatedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "homeSlides";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "homeSlides" FOR EACH ROW EXECUTE FUNCTION "touch_homeSlides"();

CREATE TABLE IF NOT EXISTS "homeSlideSeedState" (
    "seedKey"  VARCHAR(64) NOT NULL,
    "seededAt" TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("seedKey")
);

CREATE TABLE IF NOT EXISTS "users" (
    "id"                    BIGINT  NOT NULL CHECK ("id" >= 0),
    "username"              VARCHAR(255)    NOT NULL DEFAULT '',
    "avatarUrl"             TEXT            DEFAULT NULL,
    "deletedAt"             TIMESTAMPTZ        DEFAULT NULL,
    "deletedBy"             BIGINT  DEFAULT NULL CHECK ("deletedBy" >= 0),
    "passwordHash"          VARCHAR(255)    DEFAULT NULL,
    "ip"                    VARCHAR(64)     DEFAULT NULL,
    "country"               VARCHAR(8)      DEFAULT NULL,
    "balance"               DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "heldBalance"           DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "xp"                    DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "role"                  TEXT NOT NULL DEFAULT 'USER' CHECK ("role" IN ('USER','MOD','DEV','ADMIN','OWNER','BOT')),
    "perms"                 SMALLINT  NOT NULL DEFAULT 0 CHECK ("perms" >= 0),
    "anon"                  SMALLINT      NOT NULL DEFAULT 0,
    "banned"                SMALLINT      NOT NULL DEFAULT 0,
    "tipBan"                SMALLINT      NOT NULL DEFAULT 0,
    "rainBan"               SMALLINT      NOT NULL DEFAULT 0,
    "leaderboardBan"        SMALLINT      NOT NULL DEFAULT 0,
    "accountLock"           SMALLINT      NOT NULL DEFAULT 0,
    "sponsorLock"           SMALLINT      NOT NULL DEFAULT 0,
    "verified"              SMALLINT      NOT NULL DEFAULT 0,
    "2fa"                   VARCHAR(64)     DEFAULT NULL,
    "lastLogout"            TIMESTAMPTZ        DEFAULT NULL,
    "mutedUntil"            TIMESTAMPTZ        DEFAULT NULL,
    "mentionsEnabled"       SMALLINT      NOT NULL DEFAULT 1,
    "affiliateCode"         VARCHAR(64)     DEFAULT NULL,
    "affiliateCodeLock"     SMALLINT      NOT NULL DEFAULT 0,
    "affiliateEarningsOffset" DECIMAL(20,2) NOT NULL DEFAULT 0,
    "deposited"             DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "wagered"               DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "maxPerTip"             DECIMAL(20,2)   DEFAULT NULL,
    "maxTipPerUser"         DECIMAL(20,2)   DEFAULT NULL,
    "tipAllowance"          DECIMAL(20,2)   DEFAULT NULL,
    "rainTipAllowance"      DECIMAL(20,2)   DEFAULT NULL,
    "cryptoAllowance"       DECIMAL(20,2)   DEFAULT NULL,
    "steamId"               VARCHAR(32)     DEFAULT NULL,
    "googleId"              VARCHAR(64)     DEFAULT NULL,
    "steamTradeUrl"         VARCHAR(255)    DEFAULT NULL,
    "steamApiKey"           VARCHAR(64)     DEFAULT NULL,
    "selfLockUntil"         TIMESTAMPTZ        DEFAULT NULL,
    "soundEnabled"          SMALLINT      NOT NULL DEFAULT 1,
    "visualEffects"         SMALLINT      NOT NULL DEFAULT 1,
    "notificationsEnabled"  SMALLINT      NOT NULL DEFAULT 1,
    "createdAt"             TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_affiliateCode" UNIQUE ("affiliateCode"),
    CONSTRAINT "uq_steamId" UNIQUE ("steamId"),
    CONSTRAINT "uq_googleId" UNIQUE ("googleId")
);

CREATE TABLE IF NOT EXISTS "emailAccounts" (
    "userId" BIGINT NOT NULL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "bets" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "winnings"  DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "edge"      DECIMAL(10,4)   NOT NULL DEFAULT 0,
    "game"      VARCHAR(32)     NOT NULL,
    "gameId"    BIGINT  DEFAULT NULL CHECK ("gameId" >= 0),
    "completed" SMALLINT      NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_bets_userId" ON "bets" ("userId");

CREATE INDEX IF NOT EXISTS "idx_bets_completed" ON "bets" ("completed");

CREATE INDEX IF NOT EXISTS "idx_bets_game" ON "bets" ("game");

CREATE TABLE IF NOT EXISTS "transactions" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "type"      TEXT NOT NULL CHECK ("type" IN ('deposit','withdraw','in','out')),
    "method"    VARCHAR(64)     NOT NULL,
    "methodId"  BIGINT  DEFAULT NULL CHECK ("methodId" >= 0),
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_tx_userId" ON "transactions" ("userId");

CREATE INDEX IF NOT EXISTS "idx_tx_type_method" ON "transactions" ("type","method");

CREATE TABLE IF NOT EXISTS "paymentTransactions" (
    "id"             BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "internalRef"    VARCHAR(36)     NOT NULL,
    "userId"         BIGINT  NOT NULL CHECK ("userId" >= 0),
    "type"           TEXT NOT NULL CHECK ("type" IN ('deposit','withdrawal')),
    "provider"       VARCHAR(32)     NOT NULL DEFAULT 'skindeck',
    "providerRef"    VARCHAR(255)    DEFAULT NULL,
    "status"         VARCHAR(64)     NOT NULL DEFAULT 'initiating',
    "providerStatus" VARCHAR(64)     DEFAULT NULL,
    "skinItems"      JSON            DEFAULT NULL,
    "value"          DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "providerValue"  DECIMAL(20,8)   DEFAULT NULL,
    "providerCurrency" VARCHAR(16)   DEFAULT NULL,
    "lastError"      VARCHAR(512)    DEFAULT NULL,
    "finalizedAt"    TIMESTAMPTZ        DEFAULT NULL,
    "createdAt"      TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"      TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_paymentTransactions_internalRef" UNIQUE ("internalRef"),
    CONSTRAINT "uq_paymentTransactions_providerRef" UNIQUE ("providerRef")
);

CREATE INDEX IF NOT EXISTS "idx_paymentTransactions_user_created" ON "paymentTransactions" ("userId", "createdAt");

CREATE INDEX IF NOT EXISTS "idx_paymentTransactions_provider_status" ON "paymentTransactions" ("provider", "status", "updatedAt");

CREATE OR REPLACE FUNCTION "touch_paymentTransactions"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."updatedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "paymentTransactions";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "paymentTransactions" FOR EACH ROW EXECUTE FUNCTION "touch_paymentTransactions"();

CREATE TABLE IF NOT EXISTS "cases" (
    "id"            BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "name"          VARCHAR(255)    NOT NULL,
    "slug"          VARCHAR(128)    NOT NULL,
    "img"           VARCHAR(512)    DEFAULT NULL,
    "creatorId"     BIGINT  DEFAULT NULL CHECK ("creatorId" >= 0),
    "commissionPct" DECIMAL(5,2)    NOT NULL DEFAULT 0,
    "openCount"     BIGINT    NOT NULL DEFAULT 0 CHECK ("openCount" >= 0),
    "likeCount"     BIGINT    NOT NULL DEFAULT 0 CHECK ("likeCount" >= 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_cases_slug" UNIQUE ("slug")
);

CREATE INDEX IF NOT EXISTS "idx_cases_creatorId" ON "cases" ("creatorId");

CREATE TABLE IF NOT EXISTS "caseVersions" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "caseId"    BIGINT  NOT NULL CHECK ("caseId" >= 0),
    "price"     DECIMAL(20,2) NOT NULL,
    "endedAt"   TIMESTAMPTZ      DEFAULT NULL,
    "createdAt" TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_caseVersions_caseId" ON "caseVersions" ("caseId");

CREATE TABLE IF NOT EXISTS "caseItems" (
    "id"             BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "caseVersionId"  BIGINT  NOT NULL CHECK ("caseVersionId" >= 0),
    "itemId"         VARCHAR(255)  DEFAULT NULL,
    "name"           VARCHAR(255)  NOT NULL,
    "img"            VARCHAR(512)  DEFAULT NULL,
    "price"          DECIMAL(20,2) NOT NULL,
    "rangeFrom"      BIGINT  NOT NULL DEFAULT 0 CHECK ("rangeFrom" >= 0),
    "rangeTo"        BIGINT  NOT NULL DEFAULT 0 CHECK ("rangeTo" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_caseItems_caseVersionId" ON "caseItems" ("caseVersionId");

CREATE TABLE IF NOT EXISTS "fairRolls" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "seed"      VARCHAR(255)    NOT NULL,
    "nonce"     BIGINT    NOT NULL DEFAULT 0 CHECK ("nonce" >= 0),
    "result"    VARCHAR(64)     DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "caseOpenings" (
    "id"             BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"         BIGINT  NOT NULL CHECK ("userId" >= 0),
    "caseVersionId"  BIGINT    NOT NULL CHECK ("caseVersionId" >= 0),
    "caseItemId"     BIGINT    NOT NULL CHECK ("caseItemId" >= 0),
    "rollId"         BIGINT  DEFAULT NULL CHECK ("rollId" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_caseOpenings_userId" ON "caseOpenings" ("userId");

CREATE TABLE IF NOT EXISTS "caseLikes" (
    "caseId"    BIGINT    NOT NULL CHECK ("caseId" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("caseId", "userId")
);

CREATE TABLE IF NOT EXISTS "communityCaseEarnings" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "caseId"    BIGINT    NOT NULL CHECK ("caseId" >= 0),
    "creatorId" BIGINT  NOT NULL CHECK ("creatorId" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "claimedAt" TIMESTAMPTZ        DEFAULT NULL,
    "expiresAt" TIMESTAMPTZ        NOT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_communityCaseEarnings_creator" ON "communityCaseEarnings" ("creatorId", "claimedAt", "expiresAt");

CREATE INDEX IF NOT EXISTS "idx_communityCaseEarnings_caseId" ON "communityCaseEarnings" ("caseId");

CREATE TABLE IF NOT EXISTS "battles" (
    "id"             BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "ownerId"        BIGINT  NOT NULL CHECK ("ownerId" >= 0),
    "ownerFunding"   SMALLINT  NOT NULL DEFAULT 0 CHECK ("ownerFunding" >= 0),
    "entryPrice"     DECIMAL(20,2) NOT NULL,
    "privKey"        VARCHAR(8)    DEFAULT NULL,
    "minLevel"       BIGINT  NOT NULL DEFAULT 0 CHECK ("minLevel" >= 0),
    "teams"          SMALLINT       NOT NULL DEFAULT 2,
    "playersPerTeam" SMALLINT       NOT NULL DEFAULT 1,
    "gamemode"       TEXT NOT NULL DEFAULT 'standard' CHECK ("gamemode" IN ('standard','crazy','group')),
    "cosmicSpin"     SMALLINT    NOT NULL DEFAULT 0,
    "serverSeed"     VARCHAR(255)  NOT NULL DEFAULT '',
    "randomTicket" VARCHAR(32) DEFAULT NULL,
    "randomProof" TEXT DEFAULT NULL,
    "EOSBlock"       BIGINT  DEFAULT NULL CHECK ("EOSBlock" >= 0),
    "clientSeed"     VARCHAR(255)  DEFAULT NULL,
    "round"          BIGINT  NOT NULL DEFAULT 0 CHECK ("round" >= 0),
    "winnerTeam"     SMALLINT       DEFAULT NULL,
    "createdAt"      TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt"      TIMESTAMPTZ      DEFAULT NULL,
    "endedAt"        TIMESTAMPTZ      DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_battles_ownerId" ON "battles" ("ownerId");

CREATE INDEX IF NOT EXISTS "idx_battles_endedAt" ON "battles" ("endedAt");

CREATE TABLE IF NOT EXISTS "battleRounds" (
    "id"            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "battleId"      BIGINT NOT NULL CHECK ("battleId" >= 0),
    "caseVersionId" BIGINT NOT NULL CHECK ("caseVersionId" >= 0),
    "round"         BIGINT NOT NULL DEFAULT 0 CHECK ("round" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_battleRounds_battleId" ON "battleRounds" ("battleId");

CREATE TABLE IF NOT EXISTS "battlePlayers" (
    "id"       BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "battleId" BIGINT    NOT NULL CHECK ("battleId" >= 0),
    "userId"   BIGINT  NOT NULL CHECK ("userId" >= 0),
    "slot"     SMALLINT         NOT NULL DEFAULT 0,
    "team"     SMALLINT         NOT NULL DEFAULT 1,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_battlePlayers_battleId" ON "battlePlayers" ("battleId");

CREATE INDEX IF NOT EXISTS "idx_battlePlayers_userId" ON "battlePlayers" ("userId");

CREATE TABLE IF NOT EXISTS "battleOpenings" (
    "id"            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "battleId"      BIGINT NOT NULL CHECK ("battleId" >= 0),
    "caseOpeningId" BIGINT  NOT NULL CHECK ("caseOpeningId" >= 0),
    "round"         BIGINT NOT NULL DEFAULT 0 CHECK ("round" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_battleOpenings_battleId" ON "battleOpenings" ("battleId");

CREATE TABLE IF NOT EXISTS "crash" (
    "id"          BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "serverSeed"  VARCHAR(255)  NOT NULL DEFAULT '',
    "crashPoint"  DECIMAL(10,2) DEFAULT NULL,
    "createdAt"   TIMESTAMPTZ      DEFAULT NULL,
    "startedAt"   TIMESTAMPTZ      DEFAULT NULL,
    "endedAt"     TIMESTAMPTZ      DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_crash_endedAt" ON "crash" ("endedAt");

CREATE TABLE IF NOT EXISTS "crashBets" (
    "id"              BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"          BIGINT  NOT NULL CHECK ("userId" >= 0),
    "roundId"         BIGINT    NOT NULL CHECK ("roundId" >= 0),
    "amount"          DECIMAL(20,2)   NOT NULL,
    "autoCashoutPoint" DECIMAL(10,2)  DEFAULT NULL,
    "cashoutPoint"    DECIMAL(10,2)   DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_crashBets_roundId" ON "crashBets" ("roundId");

CREATE INDEX IF NOT EXISTS "idx_crashBets_userId" ON "crashBets" ("userId");

CREATE TABLE IF NOT EXISTS "coinflips" (
    "id"          BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "ownerId"     BIGINT  NOT NULL CHECK ("ownerId" >= 0),
    "fire"        BIGINT  DEFAULT NULL CHECK ("fire" >= 0),
    "ice"         BIGINT  DEFAULT NULL CHECK ("ice" >= 0),
    "amount"      DECIMAL(20,2)   NOT NULL,
    "serverSeed"  VARCHAR(255)    NOT NULL DEFAULT '',
    "EOSBlock"    BIGINT  DEFAULT NULL CHECK ("EOSBlock" >= 0),
    "clientSeed"  VARCHAR(255)    DEFAULT NULL,
    "winnerSide"  TEXT DEFAULT NULL CHECK ("winnerSide" IN ('fire','ice')),
    "startedAt"   TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_coinflips_ownerId" ON "coinflips" ("ownerId");

CREATE INDEX IF NOT EXISTS "idx_coinflips_startedAt" ON "coinflips" ("startedAt");

CREATE TABLE IF NOT EXISTS "roulette" (
    "id"        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "result"    SMALLINT      DEFAULT NULL,
    "color"     SMALLINT      DEFAULT NULL,
    "createdAt" TIMESTAMPTZ     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rolledAt"  TIMESTAMPTZ     DEFAULT NULL,
    "endedAt"   TIMESTAMPTZ     DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_roulette_endedAt" ON "roulette" ("endedAt");

CREATE TABLE IF NOT EXISTS "rouletteBets" (
    "id"       BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"   BIGINT  NOT NULL CHECK ("userId" >= 0),
    "roundId"  BIGINT    NOT NULL CHECK ("roundId" >= 0),
    "color"    SMALLINT         NOT NULL,
    "amount"   DECIMAL(20,2)   NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_rouletteBets_roundId" ON "rouletteBets" ("roundId");

CREATE INDEX IF NOT EXISTS "idx_rouletteBets_userId" ON "rouletteBets" ("userId");

CREATE TABLE IF NOT EXISTS "serverSeeds" (
    "id"       BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"   BIGINT  NOT NULL CHECK ("userId" >= 0),
    "seed"     VARCHAR(255)    NOT NULL,
    "nonce"    BIGINT    NOT NULL DEFAULT 0 CHECK ("nonce" >= 0),
    "endedAt"  TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_serverSeeds_userId" ON "serverSeeds" ("userId");

CREATE TABLE IF NOT EXISTS "clientSeeds" (
    "id"       BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"   BIGINT  NOT NULL CHECK ("userId" >= 0),
    "seed"     VARCHAR(255)    NOT NULL,
    "endedAt"  TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_clientSeeds_userId" ON "clientSeeds" ("userId");

CREATE TABLE IF NOT EXISTS "mines" (
    "id"             BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"         BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"         DECIMAL(20,2)   NOT NULL,
    "clientSeedId"   BIGINT    NOT NULL CHECK ("clientSeedId" >= 0),
    "serverSeedId"   BIGINT    NOT NULL CHECK ("serverSeedId" >= 0),
    "nonce"          BIGINT    NOT NULL DEFAULT 0 CHECK ("nonce" >= 0),
    "minesCount"     SMALLINT  NOT NULL DEFAULT 1 CHECK ("minesCount" >= 0),
    "mines"          TEXT            DEFAULT NULL,
    "revealedTiles"  TEXT            DEFAULT NULL,
    "payout"         DECIMAL(20,2)   DEFAULT NULL,
    "endedAt"        TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_mines_userId" ON "mines" ("userId");

CREATE TABLE IF NOT EXISTS "blackjack" (
    "id"           BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"       BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"       DECIMAL(20,2)   NOT NULL,
    "clientSeedId" BIGINT    NOT NULL CHECK ("clientSeedId" >= 0),
    "serverSeedId" BIGINT    NOT NULL CHECK ("serverSeedId" >= 0),
    "nonce"        BIGINT    NOT NULL DEFAULT 0 CHECK ("nonce" >= 0),
    "actions"      TEXT            DEFAULT NULL,
    "payout"       DECIMAL(20,2)   DEFAULT NULL,
    "endedAt"      TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_blackjack_userId" ON "blackjack" ("userId");

CREATE TABLE IF NOT EXISTS "slots" (
    "id"               BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "name"             VARCHAR(255) NOT NULL,
    "slug"             VARCHAR(128) NOT NULL,
    "img"              VARCHAR(512) DEFAULT NULL,
    "provider"         VARCHAR(64)  DEFAULT NULL,
    "rtp"              DECIMAL(5,2) DEFAULT NULL,
    "version"          VARCHAR(64)  DEFAULT NULL,
    "versionUpdatedAt" TIMESTAMPTZ     DEFAULT NULL,
    "providerGameId"   VARCHAR(128) DEFAULT NULL,
    "enabled"          SMALLINT   NOT NULL DEFAULT 1,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_slots_slug" UNIQUE ("slug")
);

CREATE TABLE IF NOT EXISTS "rains" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "host"      BIGINT  DEFAULT NULL CHECK ("host" >= 0),
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt"   TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_rains_endedAt" ON "rains" ("endedAt");

CREATE TABLE IF NOT EXISTS "rainUsers" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "rainId"    BIGINT    NOT NULL CHECK ("rainId" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"    DECIMAL(20,2)   DEFAULT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_rainUsers_rainId" ON "rainUsers" ("rainId");

CREATE INDEX IF NOT EXISTS "idx_rainUsers_userId" ON "rainUsers" ("userId");

CREATE TABLE IF NOT EXISTS "rainTips" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "rainId"    BIGINT    NOT NULL CHECK ("rainId" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_rainTips_rainId" ON "rainTips" ("rainId");

CREATE INDEX IF NOT EXISTS "idx_rainTips_userId" ON "rainTips" ("userId");

CREATE TABLE IF NOT EXISTS "chatMessages" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "type"      TEXT NOT NULL DEFAULT 'user' CHECK ("type" IN ('user','system','rain-tip','rain-end','clear')),
    "senderId"  BIGINT  DEFAULT NULL CHECK ("senderId" >= 0),
    "content"   TEXT            DEFAULT NULL,
    "channelId" VARCHAR(8)      DEFAULT NULL,
    "replyTo"   BIGINT  DEFAULT NULL CHECK ("replyTo" >= 0),
    "deletedAt" TIMESTAMPTZ        DEFAULT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_chatMessages_senderId" ON "chatMessages" ("senderId");

CREATE INDEX IF NOT EXISTS "idx_chatMessages_channelId" ON "chatMessages" ("channelId");

CREATE INDEX IF NOT EXISTS "idx_chatMessages_createdAt" ON "chatMessages" ("createdAt");

CREATE TABLE IF NOT EXISTS "bannedPhrases" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "phrase"    VARCHAR(512)    NOT NULL,
    "addedBy"   BIGINT  DEFAULT NULL CHECK ("addedBy" >= 0),
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "features" (
    "id"      VARCHAR(64) NOT NULL,
    "enabled" SMALLINT  NOT NULL DEFAULT 1,
    PRIMARY KEY ("id")
);

INSERT INTO "features" ("id", "enabled") VALUES
    ('battles', 1),
    ('cases', 1),
    ('coinflip', 1),
    ('crash', 1),
    ('roulette', 1),
    ('mines', 1),
    ('blackjack', 1),
    ('slots', 1),
    ('chat', 1),
    ('rain', 1),
    ('leaderboard', 1),
    ('rakeback', 1),
    ('promoCodes', 1),
    ('affiliates', 1),
    ('surveys', 1),
    ('cryptoDeposits', 1),
    ('fiatDeposits', 1),
    ('cryptoWithdrawals', 1),
    ('skindeck', 1),
    ('rainCaptcha', 1),
    ('rainDailyDepositRequirement', 1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "notifications" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "type"      VARCHAR(64)     NOT NULL,
    "content"   TEXT            DEFAULT NULL,
    "seen"      SMALLINT      NOT NULL DEFAULT 0,
    "deleted"   SMALLINT      NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_notifications_userId" ON "notifications" ("userId");

CREATE TABLE IF NOT EXISTS "cryptos" (
    "id"          VARCHAR(32)   NOT NULL,
    "name"        VARCHAR(128)  NOT NULL,
    "coingeckoId" VARCHAR(128)  NOT NULL,
    "price"       DECIMAL(20,8) NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

INSERT INTO "cryptos" ("id", "name", "coingeckoId", "price") VALUES
    ('BTC',         'Bitcoin',        'bitcoin',          0),
    ('ETH',         'Ethereum',       'ethereum',         0),
    ('LTC',         'Litecoin',       'litecoin',         0),
    ('USDT.ERC20',  'Tether (ERC20)', 'tether',           0),
    ('USDC',        'USD Coin',       'usd-coin',         0),
    ('BNB.BSC',     'BNB (BEP20)',    'binancecoin',      0),
    ('BUSD.BEP20',  'BUSD (BEP20)',   'binance-usd',      0),
    ('DOGE',        'Dogecoin',       'dogecoin',         0) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "cryptoWallets" (
    "id"       BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"   BIGINT  NOT NULL CHECK ("userId" >= 0),
    "currency" VARCHAR(32)     NOT NULL,
    "address"  VARCHAR(512)    NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_cryptoWallets_userId" ON "cryptoWallets" ("userId");

CREATE TABLE IF NOT EXISTS "cryptoDeposits" (
    "id"           BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"       BIGINT  NOT NULL CHECK ("userId" >= 0),
    "currency"     VARCHAR(32)     NOT NULL,
    "cryptoAmount" DECIMAL(20,8)   NOT NULL DEFAULT 0,
    "fiatAmount"   DECIMAL(20,8)   NOT NULL DEFAULT 0,
    "coinAmount"   BIGINT    NOT NULL DEFAULT 0 CHECK ("coinAmount" >= 0),
    "txId"         VARCHAR(255)    DEFAULT NULL,
    "status"       TEXT NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','completed','failed')),
    "createdAt"    TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt"   TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_cryptoDeposits_userId" ON "cryptoDeposits" ("userId");

CREATE INDEX IF NOT EXISTS "idx_cryptoDeposits_status" ON "cryptoDeposits" ("status");

CREATE OR REPLACE FUNCTION "touch_cryptoDeposits"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."modifiedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "cryptoDeposits";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "cryptoDeposits" FOR EACH ROW EXECUTE FUNCTION "touch_cryptoDeposits"();

CREATE TABLE IF NOT EXISTS "cryptoWithdraws" (
    "id"           BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"       BIGINT  NOT NULL CHECK ("userId" >= 0),
    "coinAmount"   DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "fiatAmount"   DECIMAL(20,8)   NOT NULL DEFAULT 0,
    "cryptoAmount" DECIMAL(20,8)   NOT NULL DEFAULT 0,
    "address"      VARCHAR(512)    NOT NULL DEFAULT '',
    "currency"     VARCHAR(32)     NOT NULL DEFAULT '',
    "chain"        VARCHAR(64)     DEFAULT NULL,
    "exchangeId"   VARCHAR(255)    DEFAULT NULL,
    "txId"         VARCHAR(255)    DEFAULT NULL,
    "status"       TEXT NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','sending','sent','completed','failed','cancelled')),
    "createdAt"    TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt"   TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_cryptoWithdraws_userId" ON "cryptoWithdraws" ("userId");

CREATE INDEX IF NOT EXISTS "idx_cryptoWithdraws_status" ON "cryptoWithdraws" ("status");

CREATE OR REPLACE FUNCTION "touch_cryptoWithdraws"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."modifiedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "cryptoWithdraws";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "cryptoWithdraws" FOR EACH ROW EXECUTE FUNCTION "touch_cryptoWithdraws"();

CREATE TABLE IF NOT EXISTS "cardDeposits" (
    "id"         BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"     BIGINT  NOT NULL CHECK ("userId" >= 0),
    "fiatAmount" DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "completed"  SMALLINT      NOT NULL DEFAULT 0,
    "modifiedAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_cardDeposits_userId" ON "cardDeposits" ("userId");

CREATE OR REPLACE FUNCTION "touch_cardDeposits"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."modifiedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "cardDeposits";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "cardDeposits" FOR EACH ROW EXECUTE FUNCTION "touch_cardDeposits"();

CREATE TABLE IF NOT EXISTS "giftCards" (
    "id"         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "code"       VARCHAR(32)  NOT NULL,
    "amount"     BIGINT NOT NULL DEFAULT 0 CHECK ("amount" >= 0),
    "usd"        SMALLINT   NOT NULL DEFAULT 0,
    "redeemedAt" TIMESTAMPTZ     DEFAULT NULL,
    "redeemedBy" BIGINT  DEFAULT NULL CHECK ("redeemedBy" >= 0),
    "notes"      VARCHAR(500) DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_giftCards_code" UNIQUE ("code")
);

CREATE INDEX IF NOT EXISTS "idx_giftCards_redeemedAt" ON "giftCards" ("redeemedAt");

CREATE TABLE IF NOT EXISTS "affiliates" (
    "id"               BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"           BIGINT  NOT NULL CHECK ("userId" >= 0),
    "affiliateId"      BIGINT  NOT NULL CHECK ("affiliateId" >= 0),
    "affiliateReward"  DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "ip"               VARCHAR(64)     DEFAULT NULL,
    "createdAt"        TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_affiliates_userId" ON "affiliates" ("userId");

CREATE INDEX IF NOT EXISTS "idx_affiliates_affiliateId" ON "affiliates" ("affiliateId");

CREATE TABLE IF NOT EXISTS "affiliateClaims" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_affiliateClaims_userId" ON "affiliateClaims" ("userId");

CREATE TABLE IF NOT EXISTS "promoCodes" (
    "id"          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "code"        VARCHAR(64)  NOT NULL,
    "amount"      DECIMAL(20,2) NOT NULL DEFAULT 0,
    "totalUses"   BIGINT DEFAULT NULL CHECK ("totalUses" >= 0),
    "currentUses" BIGINT NOT NULL DEFAULT 0 CHECK ("currentUses" >= 0),
    "minLvl"      BIGINT NOT NULL DEFAULT 0 CHECK ("minLvl" >= 0),
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_promoCodes_code" UNIQUE ("code")
);

CREATE TABLE IF NOT EXISTS "promoCodeUses" (
    "id"           BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"       BIGINT  NOT NULL CHECK ("userId" >= 0),
    "promoCodeId"  BIGINT    NOT NULL CHECK ("promoCodeId" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_promoCodeUses_userId" ON "promoCodeUses" ("userId");

CREATE INDEX IF NOT EXISTS "idx_promoCodeUses_promoCodeId" ON "promoCodeUses" ("promoCodeId");

CREATE TABLE IF NOT EXISTS "leaderboards" (
    "id"        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "type"      TEXT NOT NULL CHECK ("type" IN ('daily','weekly')),
    "createdAt" DATE         NOT NULL,
    "endedAt"   DATE         DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_leaderboards_type" ON "leaderboards" ("type");

CREATE TABLE IF NOT EXISTS "leaderboardUsers" (
    "id"            BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "leaderboardId" BIGINT    NOT NULL CHECK ("leaderboardId" >= 0),
    "userId"        BIGINT  NOT NULL CHECK ("userId" >= 0),
    "position"      SMALLINT  NOT NULL DEFAULT 1 CHECK ("position" >= 0),
    "totalWagered"  DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "amountWon"     DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "createdAt"     DATE            NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_leaderboardUsers_leaderboardId" ON "leaderboardUsers" ("leaderboardId");

CREATE INDEX IF NOT EXISTS "idx_leaderboardUsers_userId" ON "leaderboardUsers" ("userId");

CREATE TABLE IF NOT EXISTS "surveys" (
    "id"            BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"        BIGINT  NOT NULL CHECK ("userId" >= 0),
    "provider"      VARCHAR(32)     NOT NULL,
    "coins"         DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "revenue"       DECIMAL(20,8)   NOT NULL DEFAULT 0,
    "createdAt"     TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "chargedbackAt" TIMESTAMPTZ        DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_surveys_userId" ON "surveys" ("userId");

CREATE INDEX IF NOT EXISTS "idx_surveys_provider" ON "surveys" ("provider");

CREATE TABLE IF NOT EXISTS "rakebackClaims" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "type"      TEXT NOT NULL CHECK ("type" IN ('instant','daily','weekly','monthly')),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_rakebackClaims_userId" ON "rakebackClaims" ("userId");

CREATE TABLE IF NOT EXISTS "discordAuths" (
    "id"     VARCHAR(32)     NOT NULL,
    "userId" BIGINT  NOT NULL CHECK ("userId" >= 0),
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_discordAuths_userId" ON "discordAuths" ("userId");

CREATE TABLE IF NOT EXISTS "earnUsers" (
    "id"        VARCHAR(32)  NOT NULL,
    "unclaimed" DECIMAL(20,2) NOT NULL DEFAULT 0,
    "elegible"  SMALLINT   NOT NULL DEFAULT 0,
    "farming"   SMALLINT   NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "earnClaims" (
    "id"          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "earnUserId"  VARCHAR(32)  NOT NULL,
    "amount"      DECIMAL(20,2) NOT NULL,
    "createdAt"   TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_earnClaims_earnUserId" ON "earnClaims" ("earnUserId");

CREATE TABLE IF NOT EXISTS "earnPayouts" (
    "id"         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "amount"     DECIMAL(20,2) NOT NULL,
    "usersCount" BIGINT  NOT NULL DEFAULT 0 CHECK ("usersCount" >= 0),
    "createdAt"  TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "earnPayoutUsers" (
    "id"           BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "earnPayoutId" BIGINT NOT NULL CHECK ("earnPayoutId" >= 0),
    "earnUserId"   VARCHAR(32)  NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_earnPayoutUsers_payoutId" ON "earnPayoutUsers" ("earnPayoutId");

CREATE INDEX IF NOT EXISTS "idx_earnPayoutUsers_earnUserId" ON "earnPayoutUsers" ("earnUserId");

CREATE TABLE IF NOT EXISTS "dailyCaseClaims" (
    "id"        BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"    BIGINT  NOT NULL CHECK ("userId" >= 0),
    "level"     SMALLINT  NOT NULL CHECK ("level" >= 0),
    "amount"    DECIMAL(20,2)   NOT NULL,
    "createdAt" TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_dailyCaseClaims_userId_createdAt" ON "dailyCaseClaims" ("userId", "createdAt");

CREATE TABLE IF NOT EXISTS "depositCases" (
    "id"               BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"           BIGINT  NOT NULL CHECK ("userId" >= 0),
    "depositAmount"    DECIMAL(20,2)   NOT NULL,
    "casesTotal"       BIGINT    NOT NULL DEFAULT 5 CHECK ("casesTotal" >= 0),
    "casesOpened"      BIGINT    NOT NULL DEFAULT 0 CHECK ("casesOpened" >= 0),
    "wagerRequired"    DECIMAL(20,2)   NOT NULL,
    "wagerProgress"    DECIMAL(20,2)   NOT NULL DEFAULT 0,
    "active"           SMALLINT      NOT NULL DEFAULT 1,
    "expiresAt"        TIMESTAMPTZ        DEFAULT NULL,
    "createdAt"        TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_depositCases_userId_active" ON "depositCases" ("userId", "active");

CREATE INDEX IF NOT EXISTS "idx_depositCases_expiresAt" ON "depositCases" ("expiresAt");

CREATE TABLE IF NOT EXISTS "supercharges" (
    "id"            BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "userId"        BIGINT  NOT NULL CHECK ("userId" >= 0),
    "depositAmount" DECIMAL(20,2)   NOT NULL,
    "bonusAmount"   DECIMAL(20,2)   NOT NULL,
    "active"        SMALLINT      NOT NULL DEFAULT 1,
    "claimedAt"     TIMESTAMPTZ        DEFAULT NULL,
    "expiresAt"     TIMESTAMPTZ        DEFAULT NULL,
    "createdAt"     TIMESTAMPTZ        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_supercharges_userId_active" ON "supercharges" ("userId", "active");

CREATE TABLE IF NOT EXISTS "settings" (
    "id"        VARCHAR(64) NOT NULL,
    "value"     TEXT        NOT NULL,
    "updatedAt" TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id")
);

CREATE OR REPLACE FUNCTION touch_settings() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."updatedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "settings";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "settings" FOR EACH ROW EXECUTE FUNCTION touch_settings();

CREATE TABLE IF NOT EXISTS "gameSettings" (
    "id"        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" >= 0),
    "game"      VARCHAR(32)   NOT NULL,
    "key"       VARCHAR(64)   NOT NULL,
    "value"     TEXT          NOT NULL,
    "type"      TEXT NOT NULL DEFAULT 'number' CHECK ("type" IN ('number','string','boolean','json')),
    "label"     VARCHAR(128)  DEFAULT NULL,
    "description" VARCHAR(512) DEFAULT NULL,
    "min"       DECIMAL(20,8) DEFAULT NULL,
    "max"       DECIMAL(20,8) DEFAULT NULL,
    "step"      DECIMAL(20,8) DEFAULT NULL,
    "updatedAt" TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_gameSettings_game_key" UNIQUE ("game", "key")
);

CREATE OR REPLACE FUNCTION "touch_gameSettings"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW."updatedAt" = CURRENT_TIMESTAMP; RETURN NEW; END $$;

DROP TRIGGER IF EXISTS touch_timestamp ON "gameSettings";

CREATE TRIGGER touch_timestamp BEFORE UPDATE ON "gameSettings" FOR EACH ROW EXECUTE FUNCTION "touch_gameSettings"();

INSERT INTO "gameSettings" ("game", "key", "value", "type", "label", "description", "min", "max", "step") VALUES
('crash',   'houseEdge',          '4',   'number', 'House Edge (%)',   'The house edge percentage for Crash',  '0', '20', '0.5'),
('crash',   'betTime',            '10000','number','Bet Time (ms)',    'Time players have to place bets',      '1000', '60000', '500'),
('crash',   'tickRate',           '150',  'number','Tick Rate (ms)',   'Game tick interval in milliseconds',   '50', '1000', '10'),
('crash',   'maxProfit',          '1000000','number','Max Profit',     'Maximum profit per bet',               '1000', '10000000', '1000'),
('crash',   'maxPayout',          '50000','number','Max Payout',       'Maximum payout per bet',               '1000', '10000000', '1000'),
('crash',   'minBet',             '0.1',  'number','Min Bet',          'Minimum bet amount',                   '0.01', '1000', '0.01'),
('crash',   'maxBet',             '25000','number','Max Bet',          'Maximum bet amount',                   '100', '1000000', '100'),
('crash',   'bonusPotRake',       '1',    'number','Bonus Pot Rake (%)','Percent of each bet feeding the bonus pot', '0', '10', '0.1'),
('mines',   'houseEdge',          '7.5',  'number','House Edge (%)',   'The house edge percentage for Mines',  '0', '20', '0.5'),
('mines',   'totalTiles',         '25',   'number','Total Tiles',      'Total grid tiles',                     '5', '50', '1'),
('roulette','houseEdge',          '5',    'number','House Edge (%)',   'The house edge percentage for Roulette','0', '20', '0.5'),
('roulette','betTime',            '10000','number','Bet Time (ms)',    'Time players have to place bets',      '1000', '60000', '500'),
('roulette','rollTime',           '5000', 'number','Roll Time (ms)',   'Animation time for the roll',          '1000', '15000', '500'),
('roulette','maxBet',             '25000','number','Max Bet',          'Maximum bet amount',                   '100', '1000000', '100'),
('roulette','tripleGreenBonusRake','0.66','number','Triple Green Bonus Rake (%)','Portion of all coin-balance bets added to the Wheel Bonus pot','0', '5', '0.01'),
('roulette','colorsMultipliers',  '{"0":14,"1":2,"2":2,"3":7}', 'json','Color Multipliers','Payout multipliers per color', NULL, NULL, NULL),
('coinflip','houseEdge',          '5',    'number','House Edge (%)',   'The house edge percentage for Coinflip','0', '20', '0.5'),
('blackjack','houseEdge',         '2.5',  'number','House Edge (%)',   'The house edge percentage for Blackjack','0', '20', '0.5'),
('cases',   'commissionPct',      '0',    'number','Commission (%)',   'Default commission for case creators',  '0', '100', '1'),
('cases',   'topDropPrice',       '25000','number','Top Drop Price',   'Minimum item price for top drops',      '1000', '1000000', '1000'),
('battles', 'houseEdge',          '10',   'number','House Edge (%)',   'The house edge percentage for Battles', '0', '20', '0.5') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS "staffChatSettings" (
    "userId" BIGINT NOT NULL,
    "enabled" SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY ("userId")
);

CREATE TABLE IF NOT EXISTS "staffChatMessages" (
    "messageId" BIGINT NOT NULL,
    PRIMARY KEY ("messageId")
);

CREATE TABLE IF NOT EXISTS "gameOperationControls" (
    "game" VARCHAR(32) NOT NULL,
    "gameId" BIGINT NOT NULL DEFAULT 0,
    "revision" BIGINT NOT NULL DEFAULT 0,
    "pausedAt" TIMESTAMPTZ DEFAULT NULL,
    "locked" SMALLINT NOT NULL DEFAULT 0,
    "cancelledAt" TIMESTAMPTZ DEFAULT NULL,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("game", "gameId")
);

CREATE TABLE IF NOT EXISTS "gameOperationAudit" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "requestId" VARCHAR(64) NOT NULL,
    "adminId" BIGINT NOT NULL,
    "game" VARCHAR(32) NOT NULL,
    "gameId" BIGINT NOT NULL,
    "action" VARCHAR(64) NOT NULL,
    "stateBefore" TEXT DEFAULT NULL,
    "stateAfter" TEXT DEFAULT NULL,
    "parameters" TEXT DEFAULT NULL,
    "success" SMALLINT NOT NULL DEFAULT 0,
    "errorCode" VARCHAR(80) DEFAULT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_gameOperationAudit_requestId" UNIQUE ("requestId")
);

CREATE INDEX IF NOT EXISTS "idx_gameOperationAudit_game" ON "gameOperationAudit" ("game", "gameId", "id");

CREATE TABLE IF NOT EXISTS "gameRoundRules" (
    "game" VARCHAR(32) NOT NULL,
    "gameId" BIGINT NOT NULL,
    "config" TEXT NOT NULL,
    PRIMARY KEY ("game", "gameId")
);

CREATE TABLE IF NOT EXISTS "gameOperationHealth" (
    "game" VARCHAR(32) NOT NULL,
    "nodeId" VARCHAR(64) NOT NULL,
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "errorCode" VARCHAR(80) DEFAULT NULL,
    "failedAt" TIMESTAMPTZ DEFAULT NULL,
    PRIMARY KEY ("game")
);

CREATE TABLE IF NOT EXISTS "gameOperationPresence" (
    "socketId" VARCHAR(128) NOT NULL,
    "userId" BIGINT DEFAULT NULL,
    "nodeId" VARCHAR(64) NOT NULL,
    "lastSeen" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("socketId")
);

CREATE INDEX IF NOT EXISTS "idx_gameOperationPresence_lastSeen" ON "gameOperationPresence" ("lastSeen");

ALTER TABLE roulette ADD COLUMN IF NOT EXISTS "serverSeed" VARCHAR(255);

ALTER TABLE "fairRolls" ADD COLUMN IF NOT EXISTS "serverSeed" VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE "fairRolls" ADD COLUMN IF NOT EXISTS "clientSeed" VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "discordId" VARCHAR(32);

ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS token VARCHAR(512);

ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMPTZ;

ALTER TABLE "discordAuths" ADD COLUMN IF NOT EXISTS "refreshToken" VARCHAR(512);

-- Runtime additions missing from the legacy MySQL base schema.
-- Applied after the generated schema when bootstrapping a fresh Neon database.
ALTER TABLE users ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "deletedBy" BIGINT;
ALTER TABLE "discordAuths" ALTER COLUMN id SET DEFAULT replace(gen_random_uuid()::text, '-', '');
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS ip VARCHAR(64);
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS token TEXT;
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS "refreshToken" TEXT;
ALTER TABLE "earnUsers" ADD COLUMN IF NOT EXISTS "tokenExpiresAt" TIMESTAMPTZ;
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS "transactionId" VARCHAR(255);
ALTER TABLE surveys ADD COLUMN IF NOT EXISTS ip VARCHAR(64);
CREATE UNIQUE INDEX IF NOT EXISTS surveys_provider_transaction ON surveys (provider, "transactionId");
ALTER TABLE "cardDeposits" ADD COLUMN IF NOT EXISTS "orderId" VARCHAR(255);
ALTER TABLE "cardDeposits" ADD COLUMN IF NOT EXISTS "coinAmount" DECIMAL(20,2) NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS card_deposits_order ON "cardDeposits" ("orderId");

CREATE TABLE IF NOT EXISTS tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fromUserId" BIGINT NOT NULL,
    "toUserId" BIGINT NOT NULL,
    amount DECIMAL(20,2) NOT NULL CHECK (amount >= 0),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS tips_users ON tips ("fromUserId", "toUserId");

CREATE TABLE IF NOT EXISTS "hacksawSessions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sessionId" VARCHAR(255) NOT NULL UNIQUE,
    "gameId" VARCHAR(128) NOT NULL,
    "hacksawId" VARCHAR(255) NOT NULL,
    "bonusGames" TEXT NOT NULL DEFAULT '[]',
    "userId" BIGINT NOT NULL,
    "defaultBalance" DECIMAL(20,2) NOT NULL DEFAULT 0,
    balance DECIMAL(20,2) NOT NULL DEFAULT 0,
    ended SMALLINT NOT NULL DEFAULT 0 CHECK (ended IN (0, 1)),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS hacksaw_sessions_user_game ON "hacksawSessions" ("userId", "gameId", ended);

CREATE TABLE IF NOT EXISTS "slotsSpins" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    "providerSpinId" VARCHAR(255) NOT NULL,
    "betInfo" TEXT,
    "userId" BIGINT NOT NULL,
    "sessionId" BIGINT NOT NULL,
    "slotId" BIGINT NOT NULL,
    amount DECIMAL(20,2) NOT NULL DEFAULT 0,
    payout DECIMAL(20,2) NOT NULL DEFAULT 0,
    status VARCHAR(64) NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, "providerSpinId")
);
CREATE INDEX IF NOT EXISTS slots_spins_session ON "slotsSpins" ("sessionId", status);
